const reviewTreeQuality = {
  sections0: 9,
  sections1: 8,
  sections2: 6,
  segments0: 9,
  segments1: 7,
  segments2: 5,
  leafSizeVariance: 0.28,
};

const shrubBase = {
  ...reviewTreeQuality,
  levels: 2,
  angle1: 82,
  angle2: 62,
  start1: 0.1,
  start2: 0.18,
  taper0: 0.8,
  taper1: 0.72,
};

const dryTreeBase = {
  ...reviewTreeQuality,
  levels: 2,
  angle1: 76,
  angle2: 58,
  start1: 0.16,
  start2: 0.2,
  taper0: 0.82,
  taper1: 0.74,
};

const compactTreeBase = {
  ...reviewTreeQuality,
  levels: 2,
  angle1: 66,
  angle2: 50,
  start1: 0.2,
  start2: 0.22,
  taper0: 0.84,
  taper1: 0.76,
};

export const generatedTreePresets = {
  paloSanto: {
    id: 'palo-santo-generated',
    label: 'Palo santo / Bursera graveolens',
    note: 'Crooked pale dry-zone tree candidate with sparse seasonal foliage.',
    variants: [
      {
        ...dryTreeBase,
        basePreset: 'Bush 2',
        seed: 1868,
        forceX: 0.42,
        forceY: 0.12,
        forceZ: 0.18,
        forceStrength: 0.03,
        trunkLength: 2.7,
        branchLength1: 1.8,
        branchLength2: 0.68,
        trunkRadius: 0.28,
        branchRadius1: 0.13,
        branchRadius2: 0.06,
        children0: 4,
        children1: 2,
        gnarliness0: 0.48,
        gnarliness1: 0.52,
        leafCount: 18,
        leafSize: 0.11,
        barkColor: '#ae936b',
        leafColor: '#b5b37f',
        alphaTest: 0.34,
      },
      {
        ...dryTreeBase,
        basePreset: 'Bush 3',
        seed: 1875,
        forceX: -0.36,
        forceY: 0.08,
        forceZ: -0.22,
        forceStrength: 0.034,
        trunkLength: 2.45,
        branchLength1: 1.75,
        branchLength2: 0.62,
        trunkRadius: 0.26,
        branchRadius1: 0.12,
        branchRadius2: 0.058,
        children0: 5,
        children1: 2,
        gnarliness0: 0.54,
        gnarliness1: 0.48,
        leafCount: 14,
        leafSize: 0.1,
        barkColor: '#b79a70',
        leafColor: '#aaa873',
        alphaTest: 0.34,
      },
      {
        ...dryTreeBase,
        basePreset: 'Oak Small',
        seed: 1881,
        forceX: 0.16,
        forceY: 0.14,
        forceZ: 0.4,
        forceStrength: 0.028,
        trunkLength: 2.95,
        branchLength1: 1.65,
        branchLength2: 0.64,
        trunkRadius: 0.3,
        branchRadius1: 0.14,
        branchRadius2: 0.064,
        children0: 4,
        children1: 2,
        gnarliness0: 0.44,
        gnarliness1: 0.48,
        leafCount: 12,
        leafSize: 0.105,
        barkColor: '#a88a60',
        leafColor: '#b9b782',
        alphaTest: 0.36,
      },
    ],
  },
  guayabillo: {
    id: 'guayabillo',
    label: 'Guayabillo / Psidium galapageium',
    note: 'Endemic small tree candidate for higher dry and transition edges.',
    variants: [
      {
        ...compactTreeBase,
        basePreset: 'Oak Small',
        seed: 1882,
        forceX: 0.08,
        forceY: 0.28,
        forceZ: -0.08,
        forceStrength: 0.016,
        trunkLength: 2.4,
        branchLength1: 1.65,
        branchLength2: 0.72,
        trunkRadius: 0.3,
        branchRadius1: 0.16,
        branchRadius2: 0.078,
        children0: 7,
        children1: 4,
        gnarliness0: 0.12,
        gnarliness1: 0.16,
        leafCount: 120,
        leafSize: 0.115,
        barkColor: '#806f5b',
        leafColor: '#7f925e',
        alphaTest: 0.26,
      },
      {
        ...compactTreeBase,
        basePreset: 'Oak Small',
        seed: 1891,
        forceX: -0.16,
        forceY: 0.24,
        forceZ: 0.1,
        forceStrength: 0.018,
        trunkLength: 2.15,
        branchLength1: 1.8,
        branchLength2: 0.76,
        trunkRadius: 0.28,
        branchRadius1: 0.15,
        branchRadius2: 0.074,
        children0: 8,
        children1: 3,
        gnarliness0: 0.14,
        gnarliness1: 0.16,
        leafCount: 130,
        leafSize: 0.11,
        barkColor: '#88745e',
        leafColor: '#849660',
        alphaTest: 0.26,
      },
      {
        ...compactTreeBase,
        basePreset: 'Ash Small',
        seed: 1904,
        forceX: 0.02,
        forceY: 0.3,
        forceZ: 0.16,
        forceStrength: 0.014,
        trunkLength: 2.7,
        branchLength1: 1.55,
        branchLength2: 0.7,
        trunkRadius: 0.32,
        branchRadius1: 0.16,
        branchRadius2: 0.08,
        children0: 6,
        children1: 4,
        gnarliness0: 0.1,
        gnarliness1: 0.14,
        leafCount: 110,
        leafSize: 0.12,
        barkColor: '#7d6c58',
        leafColor: '#778c5b',
        alphaTest: 0.26,
      },
    ],
  },
  pagaPaga: {
    id: 'paga-paga',
    label: 'Paga-paga / Pisonia floribunda',
    note: 'Broad low arid-zone small tree; current runtime candidate for upland clusters.',
    variants: [
      {
        ...dryTreeBase,
        basePreset: 'Oak Small',
        seed: 1835,
        forceX: 0.35,
        forceY: 0.18,
        forceZ: -0.16,
        forceStrength: 0.022,
        trunkLength: 2.0,
        branchLength1: 1.9,
        branchLength2: 0.78,
        trunkRadius: 0.26,
        branchRadius1: 0.14,
        branchRadius2: 0.068,
        children0: 6,
        children1: 3,
        gnarliness0: 0.2,
        gnarliness1: 0.26,
        leafCount: 90,
        leafSize: 0.13,
        barkColor: '#806f57',
        leafColor: '#9ea36e',
        alphaTest: 0.28,
      },
      {
        ...dryTreeBase,
        basePreset: 'Bush 1',
        seed: 1841,
        forceX: -0.3,
        forceY: 0.2,
        forceZ: 0.24,
        forceStrength: 0.024,
        trunkLength: 1.75,
        branchLength1: 2.0,
        branchLength2: 0.82,
        trunkRadius: 0.24,
        branchRadius1: 0.13,
        branchRadius2: 0.064,
        children0: 7,
        children1: 3,
        gnarliness0: 0.26,
        gnarliness1: 0.28,
        leafCount: 98,
        leafSize: 0.125,
        barkColor: '#8b7659',
        leafColor: '#949d68',
        alphaTest: 0.28,
      },
      {
        ...dryTreeBase,
        basePreset: 'Oak Small',
        seed: 1859,
        forceX: 0.18,
        forceY: 0.16,
        forceZ: 0.36,
        forceStrength: 0.026,
        trunkLength: 2.25,
        branchLength1: 1.75,
        branchLength2: 0.74,
        trunkRadius: 0.27,
        branchRadius1: 0.14,
        branchRadius2: 0.068,
        children0: 5,
        children1: 3,
        gnarliness0: 0.22,
        gnarliness1: 0.3,
        leafCount: 78,
        leafSize: 0.14,
        barkColor: '#77664e',
        leafColor: '#a6aa78',
        alphaTest: 0.3,
      },
    ],
  },
  scalesia: {
    id: 'scalesia-generated',
    label: 'Scalesia / Scalesia villosa-style candidate',
    note: 'Endemic higher-zone tree-form study; Aspen base is used only for branching geometry.',
    variants: [
      {
        ...compactTreeBase,
        basePreset: 'Aspen Small',
        seed: 1952,
        forceX: 0.04,
        forceY: 0.38,
        forceZ: 0.06,
        forceStrength: 0.014,
        trunkLength: 3.0,
        branchLength1: 1.7,
        branchLength2: 0.78,
        trunkRadius: 0.28,
        branchRadius1: 0.14,
        branchRadius2: 0.07,
        children0: 7,
        children1: 4,
        gnarliness0: 0.1,
        gnarliness1: 0.14,
        leafCount: 130,
        leafSize: 0.12,
        barkColor: '#85745e',
        leafColor: '#829963',
        alphaTest: 0.26,
      },
      {
        ...compactTreeBase,
        basePreset: 'Aspen Small',
        seed: 1964,
        forceX: -0.12,
        forceY: 0.36,
        forceZ: 0.08,
        forceStrength: 0.016,
        trunkLength: 2.75,
        branchLength1: 1.85,
        branchLength2: 0.82,
        trunkRadius: 0.27,
        branchRadius1: 0.135,
        branchRadius2: 0.068,
        children0: 8,
        children1: 4,
        gnarliness0: 0.12,
        gnarliness1: 0.15,
        leafCount: 140,
        leafSize: 0.115,
        barkColor: '#8d7a62',
        leafColor: '#879d68',
        alphaTest: 0.26,
      },
      {
        ...compactTreeBase,
        basePreset: 'Ash Small',
        seed: 1977,
        forceX: 0.1,
        forceY: 0.34,
        forceZ: -0.12,
        forceStrength: 0.016,
        trunkLength: 3.25,
        branchLength1: 1.55,
        branchLength2: 0.74,
        trunkRadius: 0.3,
        branchRadius1: 0.15,
        branchRadius2: 0.074,
        children0: 7,
        children1: 4,
        gnarliness0: 0.1,
        gnarliness1: 0.14,
        leafCount: 122,
        leafSize: 0.12,
        barkColor: '#80705b',
        leafColor: '#7f9662',
        alphaTest: 0.26,
      },
    ],
  },
};

const rawEzTreePresets = ['Bush 1', 'Bush 2', 'Bush 3', 'Oak Small', 'Ash Small', 'Aspen Small'];

const tunedGeneratedTreeBrowserAssets = Object.values(generatedTreePresets).map(preset => ({
  id: `ez-${preset.id}`,
  label: preset.label,
  note: preset.note,
  kind: 'ez-tree',
  variants: preset.variants,
}));

export const generatedTreeBrowserAssets = [
  ...tunedGeneratedTreeBrowserAssets,
  ...rawEzTreePresets.map(name => ({
    id: `ez-raw-${name.toLowerCase().replace(/\s+/g, '-')}`,
    label: `EZ-Tree preset: ${name}`,
    note: 'Raw built-in ez-tree preset for comparison before Galapagos tuning.',
    kind: 'ez-tree',
    variants: [{ basePreset: name, seed: 3000 }],
  })),
];
