// Prop *type* definitions: shared physics + behavior config for each kind of
// physics prop. Instances (placed per zone) live in propRegistry.js.
//
// Behavior modules a type can opt into:
//   carryable  — E-key pickup/carry/drop (object goes kinematic while held)
//   breakable  — smashed by a tool swing; bursts into debris and grants loot
//   strikeable — tool hits knock it around instead of breaking it
//   buoyant    — floats on the sea: bobs at rideHeight above WATER_LEVEL and
//                drifts with the current (props without it sink to the seabed)
//   mobility   — explicit interaction category:
//                pickup, push, pickup-push, downhill-push, fixed, or none
//                Optional rotationPolicy keeps heavy props from tumbling like
//                hollow toys: resistTipping, autoBarrel, or free.
// Future: hinged (doors), slippery (trip hazard), avalanche triggers.

export const PROP_TYPES = {
  barrel: {
    label: 'barrel',
    visual: 'barrel',
    collider: { shape: 'cylinder', halfHeight: 0.45, radius: 0.48 },
    restOffset: 0.5,
    mass: 56,
    friction: 2.35,
    restitution: 0,
    // Heavy field objects should shove slowly, then settle quickly.
    linearDamping: 3.6,
    angularDamping: 3.5,
    behaviors: {
      mobility: {
        mode: 'push',
        assistSpeed: 0.22,
        maxSpeed: 0.36,
        contactMaxSpeed: 0.36,
        blend: 0.1,
        rotationPolicy: 'autoBarrel',
        angularMax: 1.05,
        uprightAngularMax: 0.24,
        verticalLaunchMax: 0.12,
        groundedExtraDamping: 0.65,
      },
      buoyant: { rideHeight: 0.12, strength: 34, drag: 2.4, angularDrag: 2.0, bob: 0.07, currentSpeed: 0.55 },
      breakable: {
        tool: 'hammer',
        debris: 'barrel',
        loot: {
          supplies: { food: 1, water: 1 },
          message: 'The hammer stoves in the barrel staves. Inside: ship’s biscuit still dry, and a small cask of fresh water.',
          syms: '"Whalers’ cache, sir. They won’t grudge a naturalist his biscuit."',
        },
      },
    },
  },
  postOfficeBayBarrel: {
    label: 'post office barrel',
    visual: 'barrel',
    visualAsset: 'postOfficeBayBarrel',
    collider: { shape: 'cylinder', halfHeight: 0.74, radius: 0.82 },
    restOffset: 0.82,
    fixed: true,
    mass: 80,
    friction: 1.05,
    restitution: 0.04,
    linearDamping: 1.2,
    angularDamping: 1.6,
    behaviors: {
      mobility: { mode: 'fixed' },
      buoyant: { rideHeight: 0.06, strength: 28, drag: 3.2, angularDrag: 3.4, bob: 0.04, currentSpeed: 0.22 },
      breakable: {
        tool: 'hammer',
        debris: 'barrel',
        loot: {
          supplies: { food: 1, water: 1, labels: 2 },
          message: 'The old post barrel bursts into weathered staves. Inside are a few dry biscuits, a small water cask, and spare labels.',
          syms: '"That was rather direct, sir. Still, the labels are usable."',
        },
      },
    },
  },
  crate: {
    label: 'crate',
    visual: 'crate',
    collider: { shape: 'cuboid', halfExtents: [0.48, 0.42, 0.48] },
    restOffset: 0.46,
    mass: 78,
    friction: 2.55,
    restitution: 0,
    linearDamping: 4.0,
    angularDamping: 3.8,
    behaviors: {
      mobility: {
        mode: 'push',
        assistSpeed: 0.18,
        maxSpeed: 0.3,
        contactMaxSpeed: 0.3,
        blend: 0.08,
        rotationPolicy: 'resistTipping',
        angularMax: 0.22,
        verticalLaunchMax: 0.1,
        groundedExtraDamping: 0.7,
      },
      buoyant: { rideHeight: 0.05, strength: 30, drag: 2.8, angularDrag: 2.6, bob: 0.05, currentSpeed: 0.4 },
      breakable: {
        tool: 'hammer',
        debris: 'crate',
        loot: {
          supplies: { labels: 4, spareJars: 1, twine: 1 },
          message: 'The crate splits along its slats. Packed in straw: spare labels, a stoppered jar, and good waxed twine.',
          syms: '"Providence, sir — I was down to my last label."',
        },
      },
    },
  },
  terracottaPot: {
    label: 'terracotta pot',
    visual: 'pot',
    visualAsset: 'terracottaPot',
    collider: { shape: 'cylinder', halfHeight: 0.5, radius: 0.42 },
    restOffset: 0.51,
    mass: 18,
    friction: 1.85,
    restitution: 0,
    linearDamping: 2.35,
    angularDamping: 2.2,
    behaviors: {
      mobility: {
        mode: 'pickup-push',
        assistSpeed: 0.22,
        maxSpeed: 0.42,
        contactMaxSpeed: 0.42,
        blend: 0.1,
        rotationPolicy: 'resistTipping',
        angularMax: 0.4,
        verticalLaunchMax: 0.12,
        groundedExtraDamping: 0.55,
      },
      carryable: {
        release: 0.28,
        holdHeight: 1.02,
        holdOffset: [0.13, 0.94, 0.08],
        holdRotation: [0.06, -0.08, -0.14],
        holdScale: 0.62,
      },
      breakable: {
        tool: 'hammer',
        debris: 'crate',
        loot: {
          supplies: { labels: 1 },
          message: 'The terracotta pot cracks apart. A dry scrap of wrapping paper is tucked inside.',
          syms: '"Useful for labels, if not for pottery."',
        },
      },
    },
  },
  brokenWoodenCrate: {
    label: 'broken wooden crate',
    visual: 'crate',
    visualAsset: 'brokenWoodenCrate',
    collider: { shape: 'cuboid', halfExtents: [0.46, 0.42, 0.5] },
    restOffset: 0.43,
    mass: 52,
    friction: 2.1,
    restitution: 0,
    linearDamping: 3.0,
    angularDamping: 2.8,
    behaviors: {
      mobility: {
        mode: 'push',
        assistSpeed: 0.18,
        maxSpeed: 0.34,
        contactMaxSpeed: 0.34,
        blend: 0.1,
        rotationPolicy: 'resistTipping',
        angularMax: 0.26,
        verticalLaunchMax: 0.1,
        groundedExtraDamping: 0.65,
      },
      breakable: {
        tool: 'hammer',
        debris: 'crate',
        loot: {
          supplies: { labels: 2, twine: 1 },
          message: 'The broken crate gives way completely. Usable twine and a few dry labels spill out.',
          syms: '"No shortage of broken boxes on this shore, sir."',
        },
      },
    },
  },
  stone: {
    label: 'loose stone',
    visual: 'stone',
    collider: { shape: 'ball', radius: 0.34 },
    restOffset: 0.36,
    mass: 18,
    friction: 1.45,
    restitution: 0.02,
    linearDamping: 1.45,
    angularDamping: 0.9,
    behaviors: {
      mobility: {
        mode: 'pickup-push',
        assistSpeed: 0.24,
        maxSpeed: 0.52,
        contactMaxSpeed: 0.48,
        blend: 0.12,
        verticalLaunchMax: 0.16,
        struckMaxSpeed: 1.8,
        struckVerticalLaunchMax: 0.75,
        groundedExtraDamping: 0.35,
      },
      carryable: {
        release: 0.34,
        holdHeight: 1.02,
        holdOffset: [0.32, 1.0, 0.24],
        holdRotation: [0.08, -0.18, -0.18],
      },
      // Basalt shrugs off the hammer; it gets knocked rolling instead.
      strikeable: { tool: 'hammer', impulse: 10 },
    },
  },
  // --- Penal colony settlement props. Collider dims are world meters and
  // match the modelAssets scales; the GLBs sit foot-at-origin, so each
  // visualOffsetY drops the mesh from the collider centre to the ground.
  settlementBarrel: {
    label: 'storage barrel',
    visual: 'barrel',
    visualAsset: 'settlementBarrel',
    collider: { shape: 'cylinder', halfHeight: 0.525, radius: 0.4 },
    restOffset: 0.55,
    mass: 54,
    friction: 2.3,
    restitution: 0,
    linearDamping: 3.5,
    angularDamping: 3.4,
    visualOffsetY: -0.525,
    behaviors: {
      mobility: {
        mode: 'push',
        assistSpeed: 0.22,
        maxSpeed: 0.36,
        contactMaxSpeed: 0.36,
        blend: 0.1,
        rotationPolicy: 'autoBarrel',
        angularMax: 1.0,
        uprightAngularMax: 0.24,
        verticalLaunchMax: 0.12,
        groundedExtraDamping: 0.65,
      },
      breakable: {
        tool: 'hammer',
        debris: 'barrel',
        loot: {
          supplies: { food: 1, water: 1 },
          message: 'The barrel staves give way: dried plantain and a small cask of highland spring water.',
          syms: '"Colony stores, sir. I suspect they will notice."',
        },
      },
    },
  },
  cratesAndBags: {
    label: 'crates and grain bags',
    visual: 'crate',
    visualAsset: 'cratesAndBags',
    collider: { shape: 'cuboid', halfExtents: [1.05, 0.78, 1.12] },
    restOffset: 0.78,
    fixed: true,
    mass: 160,
    friction: 1.4,
    restitution: 0,
    linearDamping: 2.0,
    angularDamping: 2.0,
    visualOffsetY: -0.78,
    behaviors: {
      mobility: { mode: 'fixed' },
    },
  },
  settlementWheelbarrow: {
    label: 'wheelbarrow',
    visual: 'crate',
    visualAsset: 'wheelbarrow',
    collider: { shape: 'cuboid', halfExtents: [0.82, 0.38, 0.4] },
    restOffset: 0.4,
    mass: 40,
    friction: 1.8,
    restitution: 0.02,
    linearDamping: 2.4,
    angularDamping: 2.4,
    visualOffsetY: -0.38,
    behaviors: {
      mobility: {
        mode: 'push',
        assistSpeed: 0.34,
        maxSpeed: 0.48,
        contactMaxSpeed: 0.48,
        blend: 0.12,
        rotationPolicy: 'resistTipping',
        angularMax: 0.4,
        verticalLaunchMax: 0.12,
        groundedExtraDamping: 0.45,
      },
    },
  },
  waterTrough: {
    label: 'water trough',
    visual: 'crate',
    visualAsset: 'waterTrough',
    collider: { shape: 'cuboid', halfExtents: [1.0, 0.4, 0.62] },
    restOffset: 0.4,
    fixed: true,
    mass: 130,
    friction: 1.6,
    restitution: 0,
    linearDamping: 2.4,
    angularDamping: 2.4,
    visualOffsetY: -0.4,
    behaviors: {
      mobility: { mode: 'fixed' },
    },
  },
  hitchingPost: {
    label: 'hitching post',
    visual: 'crate',
    visualAsset: 'hitchingPost',
    collider: { shape: 'cylinder', halfHeight: 0.66, radius: 0.32 },
    restOffset: 0.66,
    fixed: true,
    mass: 60,
    friction: 1.4,
    restitution: 0,
    linearDamping: 2.0,
    angularDamping: 2.0,
    visualOffsetY: -0.66,
    behaviors: {
      mobility: { mode: 'fixed' },
    },
  },
  // --- Watkins Camp artifacts: small carryable relics Darwin can also
  // investigate like specimens (inspectable -> inspectableCatalog id).
  scrimshawTooth: {
    label: 'scrimshaw whale tooth',
    visual: 'tooth',
    inspectable: 'scrimshaw_tooth',
    collider: { shape: 'ball', radius: 0.13 },
    restOffset: 0.13,
    mass: 2,
    friction: 1.4,
    restitution: 0.02,
    linearDamping: 1.3,
    angularDamping: 1.2,
    behaviors: {
      mobility: { mode: 'pickup' },
      carryable: {
        release: 0.24,
        holdHeight: 1.0,
        holdOffset: [0.18, 0.96, 0.16],
        holdRotation: [0.1, -0.2, -0.12],
      },
    },
  },
  watkinsDiary: {
    label: 'weather-stained diary',
    visual: 'book',
    inspectable: 'watkins_diary',
    collider: { shape: 'cuboid', halfExtents: [0.16, 0.045, 0.12] },
    restOffset: 0.05,
    mass: 1.5,
    friction: 1.8,
    restitution: 0,
    linearDamping: 1.6,
    angularDamping: 1.6,
    behaviors: {
      mobility: { mode: 'pickup' },
      carryable: {
        release: 0.2,
        holdHeight: 1.02,
        holdOffset: [0.16, 0.98, 0.14],
        holdRotation: [0.15, -0.1, -0.08],
      },
    },
  },
  charredShellFragment: {
    label: 'charred tortoise shell',
    visual: 'shellFragment',
    inspectable: 'charred_tortoise_shell',
    collider: { shape: 'ball', radius: 0.2 },
    restOffset: 0.14,
    mass: 4,
    friction: 1.6,
    restitution: 0.01,
    linearDamping: 1.5,
    angularDamping: 1.3,
    behaviors: {
      mobility: { mode: 'pickup-push', assistSpeed: 0.2, maxSpeed: 0.4 },
      carryable: {
        release: 0.26,
        holdHeight: 1.0,
        holdOffset: [0.24, 0.94, 0.18],
        holdRotation: [0.08, -0.14, -0.14],
      },
    },
  },
  earthenwareJug: {
    label: 'earthenware jug',
    visual: 'jug',
    inspectable: 'earthenware_jug',
    collider: { shape: 'cylinder', halfHeight: 0.24, radius: 0.17 },
    restOffset: 0.25,
    mass: 6,
    friction: 1.7,
    restitution: 0,
    linearDamping: 1.9,
    angularDamping: 1.8,
    behaviors: {
      mobility: {
        mode: 'pickup-push',
        assistSpeed: 0.22,
        maxSpeed: 0.4,
        rotationPolicy: 'resistTipping',
        angularMax: 0.4,
      },
      carryable: {
        release: 0.26,
        holdHeight: 1.0,
        holdOffset: [0.15, 0.92, 0.1],
        holdRotation: [0.05, -0.08, -0.12],
      },
      breakable: {
        tool: 'hammer',
        debris: 'crate',
        loot: {
          supplies: {},
          message: 'The jug shatters. A sour ghost of rum, and a curl of paper: a tally of pumpkins traded to the whaler Sukey, 1809.',
          syms: '"So the stories are true, sir. He sold his garden for rum."',
        },
      },
    },
  },
  looseFloorBoard: {
    label: 'loose floor board',
    visual: 'looseBoard',
    collider: { shape: 'cuboid', halfExtents: [0.85, 0.035, 0.16] },
    restOffset: 0.04,
    mass: 9,
    friction: 2.0,
    restitution: 0,
    linearDamping: 2.4,
    angularDamping: 2.2,
    behaviors: {
      mobility: { mode: 'pickup-push', assistSpeed: 0.2, maxSpeed: 0.38 },
      carryable: {
        release: 0.28,
        holdHeight: 1.04,
        holdOffset: [0.2, 0.98, 0.22],
        holdRotation: [0.06, -0.12, -0.5],
        holdScale: 0.85,
      },
    },
  },
  woodenBucket: {
    label: 'wooden bucket',
    visual: 'barrel',
    visualAsset: 'woodenBucket',
    collider: { shape: 'cylinder', halfHeight: 0.17, radius: 0.21 },
    restOffset: 0.18,
    mass: 9,
    friction: 1.35,
    restitution: 0.01,
    linearDamping: 1.35,
    angularDamping: 1.25,
    visualOffsetY: -0.17,
    behaviors: {
      mobility: {
        mode: 'pickup-push',
        assistSpeed: 0.28,
        maxSpeed: 0.52,
        contactMaxSpeed: 0.5,
        blend: 0.12,
        rotationPolicy: 'resistTipping',
        angularMax: 0.45,
        verticalLaunchMax: 0.14,
        groundedExtraDamping: 0.4,
      },
      carryable: {
        release: 0.28,
        holdHeight: 0.98,
        holdOffset: [0.14, 0.9, 0.1],
        holdRotation: [0.04, -0.06, -0.1],
        holdScale: 0.8,
      },
    },
  },
  cabinChair: {
    label: 'cabin chair',
    visual: 'cabinChair',
    visualAsset: 'beagleCabinChair',
    collider: { shape: 'cuboid', halfExtents: [0.48, 0.62, 0.48] },
    restOffset: 0.63,
    mass: 24,
    friction: 2.4,
    restitution: 0,
    linearDamping: 4.2,
    angularDamping: 4.4,
    behaviors: {
      mobility: {
        mode: 'push',
        assistSpeed: 0.17,
        maxSpeed: 0.28,
        contactMaxSpeed: 0.28,
        blend: 0.08,
        rotationPolicy: 'resistTipping',
        angularMax: 0.34,
        verticalLaunchMax: 0.08,
        groundedExtraDamping: 0.82,
      },
      strikeable: { tool: 'hammer', impulse: 3.2 },
    },
  },
  cabinStool: {
    label: 'folding stool',
    visual: 'cabinStool',
    visualAsset: 'beagleCabinStool',
    collider: { shape: 'cuboid', halfExtents: [0.34, 0.38, 0.34] },
    restOffset: 0.39,
    mass: 10,
    friction: 2.0,
    restitution: 0,
    linearDamping: 3.1,
    angularDamping: 3.2,
    behaviors: {
      mobility: { mode: 'pickup-push', assistSpeed: 0.2, maxSpeed: 0.34, rotationPolicy: 'resistTipping', angularMax: 0.45 },
      carryable: {
        release: 0.3,
        holdOffset: [0.2, 0.92, 0.16],
        holdRotation: [0.08, -0.08, -0.18],
        grip: 'rightHand',
        gripOffset: [0.13, 0, 0.02],
        animationStyle: 'freeHand',
      },
      strikeable: { tool: 'hammer', impulse: 4.5 },
    },
  },
  cabinSeaChest: {
    label: 'sea chest',
    visual: 'cabinSeaChest',
    visualAsset: 'beagleCabinSeaChest',
    collider: { shape: 'cuboid', halfExtents: [0.72, 0.42, 0.46] },
    restOffset: 0.43,
    mass: 68,
    friction: 2.7,
    restitution: 0,
    linearDamping: 4.5,
    angularDamping: 4.5,
    behaviors: {
      mobility: { mode: 'push', assistSpeed: 0.14, maxSpeed: 0.24, contactMaxSpeed: 0.24, rotationPolicy: 'resistTipping', angularMax: 0.18, groundedExtraDamping: 0.9 },
      strikeable: { tool: 'hammer', impulse: 2.4 },
    },
  },
  cabinBucket: {
    label: 'cabin bucket',
    visual: 'cabinBucket',
    visualAsset: 'beagleCabinBucket',
    collider: { shape: 'cylinder', halfHeight: 0.28, radius: 0.3 },
    restOffset: 0.29,
    mass: 7,
    friction: 1.8,
    restitution: 0,
    linearDamping: 2.4,
    angularDamping: 2.2,
    behaviors: {
      mobility: { mode: 'pickup-push', assistSpeed: 0.24, maxSpeed: 0.42, rotationPolicy: 'resistTipping', angularMax: 0.55 },
      carryable: { release: 0.28, holdOffset: [0.16, 0.92, 0.1], holdRotation: [0.04, -0.08, -0.12] },
      strikeable: { tool: 'hammer', impulse: 5.2 },
    },
  },
  rolledChart: {
    label: 'rolled chart',
    visual: 'rolledChart',
    visualAsset: 'beagleCabinRolledChart',
    collider: { shape: 'cylinder', halfHeight: 0.38, radius: 0.075 },
    restOffset: 0.09,
    mass: 0.7,
    friction: 1.55,
    restitution: 0,
    linearDamping: 2.0,
    angularDamping: 1.5,
    behaviors: {
      mobility: { mode: 'pickup-push', assistSpeed: 0.25, maxSpeed: 0.48, angularMax: 1.2 },
      carryable: { release: 0.22, holdOffset: [0.18, 0.95, 0.13], holdRotation: [0.04, 0, -0.75] },
    },
  },
  chartWeight: {
    label: 'brass chart weight',
    visual: 'chartWeight',
    visualAsset: 'beagleCabinChartWeight',
    collider: { shape: 'cylinder', halfHeight: 0.075, radius: 0.13 },
    restOffset: 0.08,
    mass: 3.8,
    friction: 1.9,
    restitution: 0.01,
    linearDamping: 2.6,
    angularDamping: 2.2,
    behaviors: {
      mobility: { mode: 'pickup-push', assistSpeed: 0.18, maxSpeed: 0.32, angularMax: 0.75 },
      carryable: { release: 0.2, holdOffset: [0.16, 0.95, 0.12], holdRotation: [0, 0, -0.08] },
    },
  },
  cabinMug: {
    label: 'tin mug',
    visual: 'cabinMug',
    visualAsset: 'beagleCabinTinMug',
    collider: { shape: 'cylinder', halfHeight: 0.12, radius: 0.11 },
    restOffset: 0.13,
    mass: 0.8,
    friction: 1.5,
    restitution: 0.01,
    linearDamping: 1.8,
    angularDamping: 1.7,
    behaviors: {
      mobility: { mode: 'pickup-push', assistSpeed: 0.26, maxSpeed: 0.46, angularMax: 0.9 },
      carryable: { release: 0.2, holdOffset: [0.15, 0.95, 0.1], holdRotation: [0.04, -0.05, -0.1] },
      strikeable: { tool: 'hammer', impulse: 0.9 },
    },
  },
  cabinCandlestick: {
    label: 'brass candlestick',
    visual: 'cabinCandlestick',
    visualAsset: 'beagleCabinCandlestick',
    collider: { shape: 'cylinder', halfHeight: 0.24, radius: 0.14 },
    restOffset: 0.25,
    mass: 2.1,
    friction: 1.7,
    restitution: 0,
    linearDamping: 2.2,
    angularDamping: 2.0,
    behaviors: {
      mobility: { mode: 'pickup-push', assistSpeed: 0.2, maxSpeed: 0.36, rotationPolicy: 'resistTipping', angularMax: 0.55 },
      carryable: { release: 0.22, holdOffset: [0.14, 0.94, 0.1], holdRotation: [0.04, -0.05, -0.08] },
      strikeable: { tool: 'hammer', impulse: 1.4 },
    },
  },
  lawsonDiningChair: {
    label: 'dining chair', visual: 'cabinChair', visualAsset: 'lawsonDiningChair',
    interactionRing: false,
    visualOffsetY: -0.55, fixed: true,
    collider: { shape: 'cuboid', halfExtents: [0.31, 0.54, 0.29] }, restOffset: 0.55,
    mass: 19, friction: 2.3, restitution: 0, linearDamping: 4, angularDamping: 4.2,
    behaviors: { mobility: { mode: 'push', assistSpeed: 0.17, maxSpeed: 0.28, contactMaxSpeed: 0.28, rotationPolicy: 'resistTipping', angularMax: 0.34, groundedExtraDamping: 0.82 } },
  },
  lawsonCampaignStool: {
    label: 'campaign stool', visual: 'cabinStool', visualAsset: 'lawsonCampaignStool',
    interactionRing: false,
    visualOffsetY: -0.3,
    collider: { shape: 'cuboid', halfExtents: [0.345, 0.303, 0.29] }, restOffset: 0.303,
    mass: 8, friction: 1.9, restitution: 0, linearDamping: 3, angularDamping: 3,
    behaviors: {
      mobility: { mode: 'pickup-push', assistSpeed: 0.2, maxSpeed: 0.34, rotationPolicy: 'resistTipping', angularMax: 0.45 },
      carryable: {
        release: 0.28,
        holdOffset: [0.2, 0.92, 0.16],
        holdRotation: [0.08, -0.08, -0.18],
        grip: 'rightHand',
        gripOffset: [0.13, 0, 0.02],
        animationStyle: 'freeHand',
      },
    },
  },
  lawsonRumBottle: {
    label: 'rum bottle', visual: 'jug', visualAsset: 'lawsonRumBottle',
    interactionRing: false,
    visualOffsetY: -0.4,
    collider: { shape: 'cylinder', halfHeight: 0.39, radius: 0.14 }, restOffset: 0.4,
    mass: 1.4, friction: 1.45, restitution: 0.02, linearDamping: 2.1, angularDamping: 1.8,
    behaviors: { mobility: { mode: 'pickup-push', assistSpeed: 0.23, maxSpeed: 0.42, rotationPolicy: 'resistTipping', angularMax: 0.65 }, carryable: { release: 0.2, holdOffset: [0.14, 0.94, 0.1], holdRotation: [0.02, -0.05, -0.08] }, strikeable: { tool: 'hammer', impulse: 1.0 } },
  },
  lawsonTinMug: {
    label: 'tin mug', visual: 'cabinMug', visualAsset: 'lawsonTinMug',
    interactionRing: false,
    visualOffsetY: -0.13,
    collider: { shape: 'cylinder', halfHeight: 0.125, radius: 0.12 }, restOffset: 0.13,
    mass: 0.75, friction: 1.5, restitution: 0.01, linearDamping: 1.8, angularDamping: 1.7,
    behaviors: { mobility: { mode: 'pickup-push', assistSpeed: 0.26, maxSpeed: 0.46, angularMax: 0.9 }, carryable: { release: 0.2, holdOffset: [0.15, 0.95, 0.1], holdRotation: [0.04, -0.05, -0.1] }, strikeable: { tool: 'hammer', impulse: 0.9 } },
  },
  lawsonServingBowl: {
    label: 'serving bowl', visual: 'cabinMug', visualAsset: 'lawsonServingBowl',
    interactionRing: false,
    visualOffsetY: -0.14,
    collider: { shape: 'cylinder', halfHeight: 0.13, radius: 0.29 }, restOffset: 0.14,
    mass: 2.8, friction: 1.8, restitution: 0, linearDamping: 2.4, angularDamping: 2.2,
    behaviors: { mobility: { mode: 'pickup-push', assistSpeed: 0.18, maxSpeed: 0.32, rotationPolicy: 'resistTipping', angularMax: 0.5 }, carryable: { release: 0.22, holdOffset: [0.18, 0.92, 0.15], holdRotation: [0.04, 0, -0.08] }, strikeable: { tool: 'hammer', impulse: 1.2 } },
  },
  lawsonFoldedChart: {
    label: 'folded chart', visual: 'rolledChart', visualAsset: 'lawsonFoldedChart',
    interactionRing: false,
    visualOffsetY: -0.03,
    collider: { shape: 'cuboid', halfExtents: [0.31, 0.025, 0.21] }, restOffset: 0.03,
    mass: 0.35, friction: 1.6, restitution: 0, linearDamping: 2, angularDamping: 1.7,
    behaviors: { mobility: { mode: 'pickup-push', assistSpeed: 0.24, maxSpeed: 0.44, angularMax: 1 }, carryable: { release: 0.2, holdOffset: [0.18, 0.95, 0.12], holdRotation: [0.04, 0, -0.12] } },
  },
  lawsonSupplyLedger: {
    label: 'supply ledger', visual: 'book', visualAsset: 'lawsonSupplyLedger',
    interactionRing: false,
    visualOffsetY: -0.11,
    collider: { shape: 'cuboid', halfExtents: [0.3, 0.1, 0.4] }, restOffset: 0.11,
    mass: 1.7, friction: 1.7, restitution: 0, linearDamping: 2.2, angularDamping: 1.9,
    behaviors: { mobility: { mode: 'pickup-push', assistSpeed: 0.2, maxSpeed: 0.36, angularMax: 0.7 }, carryable: { release: 0.2, holdOffset: [0.18, 0.94, 0.12], holdRotation: [0.04, 0, -0.14] } },
  },
  lawsonCandlestick: {
    label: 'brass candlestick', visual: 'cabinCandlestick', visualAsset: 'lawsonCandlestick',
    interactionRing: false,
    visualOffsetY: -0.37,
    collider: { shape: 'cylinder', halfHeight: 0.36, radius: 0.15 }, restOffset: 0.37,
    mass: 2.2, friction: 1.75, restitution: 0, linearDamping: 2.3, angularDamping: 2.1,
    behaviors: { mobility: { mode: 'pickup-push', assistSpeed: 0.2, maxSpeed: 0.35, rotationPolicy: 'resistTipping', angularMax: 0.5 }, carryable: { release: 0.22, holdOffset: [0.14, 0.94, 0.1], holdRotation: [0.04, -0.05, -0.08] }, strikeable: { tool: 'hammer', impulse: 1.4 } },
  },
};
