export const faunaBehaviorProfiles = {
  mediumgroundfinch: {
    habitatRadiusX: 5.2,
    habitatRadiusZ: 3.2,
    walkSpeed: 0.32,
    fleeSpeed: 2.15,
    patrolRate: 0.62,
    alertRadius: 4.8,
    panicRadius: 1.25,
    hammerAlertRadius: 8.5,
    bobAmount: 0.028,
    groundOffset: 0.04,
    turnRate: 15,
    contactReaction: 'quick-hop-away',
    contactAlertRadius: 3.6,
    contactReactionDuration: 1.1,
  },
  marineiguana: {
    habitatRadiusX: 6.8,
    habitatRadiusZ: 3.6,
    walkSpeed: 0.22,
    fleeSpeed: 1.45,
    patrolRate: 0.38,
    alertRadius: 4.8,
    panicRadius: 1.35,
    hammerAlertRadius: 8.0,
    bobAmount: 0.006,
    groundOffset: 0.04,
    turnRate: 10,
    movementStyle: 'crawl',
    contactReaction: 'shuffle-away',
    contactAlertRadius: 3.2,
    contactReactionDuration: 1.2,
    orbitSpeed: 0.18,
    orbitRadiusScaleX: 0.28,
    orbitRadiusScaleZ: 0.22,
  },
  galapagospenguin: {
    habitatRadiusX: 6.2,
    habitatRadiusZ: 3.4,
    walkSpeed: 0.26,
    fleeSpeed: 1.25,
    patrolRate: 0.34,
    alertRadius: 4.6,
    panicRadius: 1.3,
    hammerAlertRadius: 7.5,
    bobAmount: 0.02,
    groundOffset: 0.04,
    turnRate: 9,
    contactReaction: 'waddle-away',
    contactAlertRadius: 3.4,
    contactReactionDuration: 1.25,
  },
  floreanagianttortoise: {
    habitatRadiusX: 4.6,
    habitatRadiusZ: 2.6,
    walkSpeed: 0.08,
    fleeSpeed: 0.32,
    patrolRate: 0.18,
    alertRadius: 3.2,
    panicRadius: 0.95,
    hammerAlertRadius: 5.5,
    bobAmount: 0.002,
    groundOffset: 0.04,
    turnRate: 4,
    contactReaction: 'slow-withdraw',
    contactAlertRadius: 2.4,
    contactReactionDuration: 2.2,
  },
  crab: {
    habitatRadiusX: 5.8,
    habitatRadiusZ: 2.8,
    walkSpeed: 0.55,
    fleeSpeed: 2.25,
    patrolRate: 0.55,
    alertRadius: 5.2,
    panicRadius: 1.55,
    bobAmount: 0.018,
    groundOffset: 0.04,
    turnRate: 14,
    movementStyle: 'scuttle',
    movementFacingMode: 'sideways',
    contactReaction: 'sideways-scuttle',
    contactAlertRadius: 3.8,
    contactReactionDuration: 1.0,
    orbitSpeed: 0.9,
    orbitRadiusScaleX: 0.34,
    orbitRadiusScaleZ: 0.26,
    scuttleFrequency: 11,
    scuttleAmplitude: 0.22,
  },
  flightlesscormorant: {
    habitatRadiusX: 8.5,
    habitatRadiusZ: 4.2,
    walkSpeed: 0.42,
    fleeSpeed: 1.15,
    patrolRate: 0.32,
    alertRadius: 6.0,
    panicRadius: 1.8,
    bobAmount: 0.025,
    groundOffset: 0.04,
    turnRate: 7,
    movementStyle: 'waddle',
    contactReaction: 'brisk-walk-away',
    contactAlertRadius: 4.2,
    contactReactionDuration: 1.35,
    orbitSpeed: 0.22,
    orbitRadiusScaleX: 0.34,
    orbitRadiusScaleZ: 0.28,
  },
  frigatebird: {
    habitatRadiusX: 10.5,
    habitatRadiusZ: 4.8,
    walkSpeed: 0.46,
    fleeSpeed: 2.85,
    patrolRate: 0.42,
    alertRadius: 8.5,
    panicRadius: 2.25,
    bobAmount: 0.018,
    groundOffset: 0.05,
    turnRate: 13,
    walkClip: 'walk',
    runClip: 'run',
    movementStyle: 'waddle',
    contactReaction: 'fast-walk-away',
    contactAlertRadius: 5.2,
    contactReactionDuration: 1.4,
    orbitSpeed: 0.24,
    orbitRadiusScaleX: 0.32,
    orbitRadiusScaleZ: 0.24,
  },
  booby: {
    habitatRadiusX: 8.2,
    habitatRadiusZ: 4.2,
    walkSpeed: 0.34,
    fleeSpeed: 1.85,
    patrolRate: 0.36,
    alertRadius: 6.2,
    panicRadius: 1.7,
    bobAmount: 0.018,
    groundOffset: 0.05,
    turnRate: 8,
    idleClip: 'idle',
    walkClip: 'walk',
    runClip: 'run',
    movementStyle: 'waddle',
    contactReaction: 'fast-walk-away',
    contactAlertRadius: 4.6,
    contactReactionDuration: 1.35,
    orbitSpeed: 0.24,
    orbitRadiusScaleX: 0.34,
    orbitRadiusScaleZ: 0.26,
  },
  lavalizard: {
    habitatRadiusX: 3.2,
    habitatRadiusZ: 1.6,
    walkSpeed: 0.35,
    fleeSpeed: 2.6,
    patrolRate: 0.7,
    alertRadius: 4.2,
    panicRadius: 1.2,
    bobAmount: 0.008,
    groundOffset: 0.04,
    turnRate: 16,
    idleClip: 'Idle',
    walkClip: 'Walk',
    runClip: 'Walk',
    movementStyle: 'dart',
    contactReaction: 'dart-away',
    contactAlertRadius: 3.8,
    contactReactionDuration: 0.9,
    orbitSpeed: 0.82,
    orbitRadiusScaleX: 0.36,
    orbitRadiusScaleZ: 0.28,
  },
};

export function getFaunaBehaviorProfile(specimen) {
  if (!specimen?.id) return null;
  return faunaBehaviorProfiles[specimen.id] || null;
}

// Animals docile enough for Darwin to pick up bare-handed. holdHeight is the
// carry height above the player's feet; heavier animals ride lower.
export const faunaCarryProfiles = {
  floreanagianttortoise: { label: 'tortoise', holdHeight: 0.7 },
  marineiguana: { label: 'marine iguana', holdHeight: 0.88 },
  galapagospenguin: { label: 'penguin', holdHeight: 0.95 },
};

export function getFaunaCarryProfile(specimen) {
  if (!specimen?.id) return null;
  return faunaCarryProfiles[specimen.id] || null;
}
