export const faunaBehaviorProfiles = {
  mediumgroundfinch: {
    habitatRadiusX: 5.2,
    habitatRadiusZ: 3.2,
    walkSpeed: 0.32,
    fleeSpeed: 2.15,
    patrolRate: 0.62,
    alertRadius: 4.8,
    panicRadius: 1.25,
    hammerAlertRadius: 8.5,
    targetInterval: [1.1, 3.2],
    dwellTime: [0.25, 0.9],
    bobAmount: 0.028,
    groundOffset: 0.04,
    turnRate: 15,
    allowedBiomes: ['dry-scrub', 'palo-santo', 'trail', 'ash-slope', 'black-lava', 'white-sand', 'black-sand', 'sesuvium-flat'],
    avoidBiomes: ['water'],
  },
  marineiguana: {
    habitatRadiusX: 6.8,
    habitatRadiusZ: 3.6,
    walkSpeed: 0.22,
    fleeSpeed: 1.45,
    patrolRate: 0.38,
    alertRadius: 4.8,
    panicRadius: 1.35,
    hammerAlertRadius: 8.0,
    targetInterval: [1.8, 4.8],
    dwellTime: [0.45, 1.4],
    bobAmount: 0.006,
    groundOffset: 0.04,
    turnRate: 10,
    allowedBiomes: ['wet-basalt', 'ash-slope', 'black-lava', 'trail', 'lava-shelf', 'black-sand'],
    avoidBiomes: ['dry-scrub', 'palo-santo'],
  },
  galapagospenguin: {
    habitatRadiusX: 6.2,
    habitatRadiusZ: 3.4,
    walkSpeed: 0.26,
    fleeSpeed: 1.25,
    patrolRate: 0.34,
    alertRadius: 4.6,
    panicRadius: 1.3,
    hammerAlertRadius: 7.5,
    targetInterval: [1.8, 4.5],
    dwellTime: [0.45, 1.5],
    bobAmount: 0.02,
    groundOffset: 0.04,
    turnRate: 9,
    allowedBiomes: ['wet-basalt', 'ash-slope', 'black-lava', 'trail', 'white-sand', 'black-sand', 'lava-shelf'],
    avoidBiomes: ['dry-scrub', 'palo-santo'],
  },
  floreanagianttortoise: {
    habitatRadiusX: 4.6,
    habitatRadiusZ: 2.6,
    walkSpeed: 0.08,
    fleeSpeed: 0.32,
    patrolRate: 0.18,
    alertRadius: 3.2,
    panicRadius: 0.95,
    hammerAlertRadius: 5.5,
    targetInterval: [3.5, 7.5],
    dwellTime: [1.0, 2.5],
    bobAmount: 0.002,
    groundOffset: 0.04,
    turnRate: 4,
    allowedBiomes: ['dry-scrub', 'palo-santo', 'trail', 'ash-slope'],
    avoidBiomes: ['water', 'wet-basalt'],
  },
  crab: {
    habitatRadiusX: 5.8,
    habitatRadiusZ: 2.8,
    walkSpeed: 0.55,
    fleeSpeed: 2.25,
    patrolRate: 0.55,
    alertRadius: 5.2,
    panicRadius: 1.55,
    targetInterval: [1.0, 3.0],
    dwellTime: [0.15, 0.65],
    bobAmount: 0.018,
    groundOffset: 0.04,
    turnRate: 14,
    cornerable: true,
    allowedBiomes: ['wet-basalt', 'ash-slope', 'black-lava', 'trail'],
    avoidBiomes: ['water', 'dry-scrub', 'palo-santo'],
  },
  flightlesscormorant: {
    habitatRadiusX: 8.5,
    habitatRadiusZ: 4.2,
    walkSpeed: 0.42,
    fleeSpeed: 1.15,
    patrolRate: 0.32,
    alertRadius: 6.0,
    panicRadius: 1.8,
    targetInterval: [2.5, 5.8],
    dwellTime: [0.65, 1.75],
    bobAmount: 0.025,
    groundOffset: 0.04,
    turnRate: 7,
    cornerable: true,
    allowedBiomes: ['wet-basalt', 'ash-slope', 'black-lava', 'trail'],
    avoidBiomes: ['water', 'dry-scrub', 'palo-santo'],
  },
  frigatebird: {
    habitatRadiusX: 10.5,
    habitatRadiusZ: 4.8,
    walkSpeed: 0.46,
    fleeSpeed: 2.85,
    patrolRate: 0.42,
    alertRadius: 8.5,
    panicRadius: 2.25,
    targetInterval: [1.8, 4.2],
    dwellTime: [0.25, 0.9],
    bobAmount: 0.018,
    groundOffset: 0.05,
    turnRate: 13,
    walkClip: 'walk',
    runClip: 'run',
    allowedBiomes: ['black-sand', 'ash-beach', 'lava-shelf', 'sesuvium-flat', 'wet-basalt', 'ash-slope', 'black-lava', 'trail', 'white-sand'],
    avoidBiomes: ['water', 'dry-scrub', 'palo-santo'],
  },
  lavalizard: {
    habitatRadiusX: 3.2,
    habitatRadiusZ: 1.6,
    walkSpeed: 0.35,
    fleeSpeed: 2.6,
    patrolRate: 0.7,
    alertRadius: 4.2,
    panicRadius: 1.2,
    targetInterval: [1.2, 4.0],
    dwellTime: [0.35, 1.2],
    bobAmount: 0.008,
    groundOffset: 0.04,
    turnRate: 16,
    allowedBiomes: ['black-lava', 'ash-slope', 'wet-basalt', 'trail'],
    avoidBiomes: ['water', 'dry-scrub'],
  },
};

export function getFaunaBehaviorProfile(specimen) {
  if (!specimen?.id) return null;
  return faunaBehaviorProfiles[specimen.id] || null;
}

// Animals docile enough for Darwin to pick up bare-handed. holdHeight is the
// carry height above the player's feet; heavier animals ride lower.
export const faunaCarryProfiles = {
  floreanagianttortoise: { label: 'tortoise', holdHeight: 0.7 },
  marineiguana: { label: 'marine iguana', holdHeight: 0.88 },
  galapagospenguin: { label: 'penguin', holdHeight: 0.95 },
};

export function getFaunaCarryProfile(specimen) {
  if (!specimen?.id) return null;
  return faunaCarryProfiles[specimen.id] || null;
}
