const SPECIES_ALIASES = {
  bluefootedbooby: 'booby',
  blue_footed_booby: 'booby',
  floreana_giant_tortoise: 'floreanagianttortoise',
  floreanagianttortoise: 'floreanagianttortoise',
  greenTurtle: 'greenturtle',
  green_turtle: 'greenturtle',
  marineIguana: 'marineiguana',
  marine_iguana: 'marineiguana',
  mediumGroundFinch: 'mediumgroundfinch',
  medium_ground_finch: 'mediumgroundfinch',
  american_flamingo: 'flamingo',
  flamingo: 'flamingo',
  gull: 'lavagull',
  lava_gull: 'lavagull',
  lavagull: 'lavagull',
  seagull: 'lavagull',
  seaLion: 'sealion',
  sea_lion: 'sealion',
  feral_cat: 'cat',
  settlement_cat: 'cat',
  feral_goat: 'feralgoat',
  goat: 'feralgoat',
  capra: 'feralgoat',
  feral_horse: 'feralhorse',
  horse: 'feralhorse',
  equus: 'feralhorse',
  jacko: 'jackothemonkey',
  jacko_the_monkey: 'jackothemonkey',
  jackothemonkey: 'jackothemonkey',
  monkey: 'jackothemonkey',
};

export function normalizeWildlifeId(input) {
  const raw = typeof input === 'string' ? input : input?.id || input?.specimenId || '';
  if (!raw) return '';
  const compact = String(raw).replace(/[^a-zA-Z0-9_]/g, '').toLowerCase();
  return SPECIES_ALIASES[raw] || SPECIES_ALIASES[compact] || compact;
}

export const wildlifeCatalog = {
  mediumgroundfinch: {
    id: 'mediumgroundfinch',
    assetId: 'mediumGroundFinch',
    englishName: 'Medium ground finch',
    latinName: 'Geospiza fortis',
    category: 'Animal',
    roleDefault: 'specimen',
    collisionRadius: 0.28,
    interactionHeight: 0.2,
    behavior: {
      controller: 'ground',
      habitatRadiusX: 5.2,
      habitatRadiusZ: 3.2,
      walkSpeed: 0.32,
      fleeSpeed: 2.15,
      patrolRate: 0.62,
      alertRadius: 4.8,
      panicRadius: 1.25,
      hammerAlertRadius: 8.5,
      bobAmount: 0.028,
      groundOffset: 0.04,
      turnRate: 15,
      idleClip: 'headTilt',
      movementStyle: 'hop',
      contactReaction: 'quick-hop-away',
      contactAlertRadius: 3.6,
      contactReactionDuration: 1.1,
      startleDuration: 0.85,
      startleSpeedMultiplier: 0.95,
      startleCooldown: 2.8,
    },
  },
  marineiguana: {
    id: 'marineiguana',
    assetId: 'marineIguana',
    englishName: 'Marine iguana',
    latinName: 'Amblyrhynchus cristatus',
    category: 'Animal',
    roleDefault: 'specimen',
    collisionRadius: 0.58,
    interactionHeight: 0.25,
    carry: { label: 'marine iguana', holdHeight: 0.88 },
    behavior: {
      controller: 'ground',
      habitatRadiusX: 6.8,
      habitatRadiusZ: 3.6,
      walkSpeed: 0.22,
      fleeSpeed: 1.45,
      patrolRate: 0.38,
      alertRadius: 4.8,
      panicRadius: 1.35,
      hammerAlertRadius: 8.0,
      bobAmount: 0.006,
      groundOffset: 0.04,
      turnRate: 10,
      idleClip: 'Iguana|Iguana|IguanaAction',
      walkClip: 'Iguana|Iguana|IguanaAction',
      runClip: 'Iguana|Iguana|IguanaAction',
      movementStyle: 'crawl',
      contactReaction: 'shuffle-away',
      contactAlertRadius: 3.2,
      contactReactionDuration: 1.2,
      orbitSpeed: 0.18,
      orbitRadiusScaleX: 0.28,
      orbitRadiusScaleZ: 0.22,
      startleDuration: 0.75,
      startleSpeedMultiplier: 0.65,
      startleCooldown: 3.1,
    },
  },
  galapagospenguin: {
    id: 'galapagospenguin',
    assetId: 'galapagosPenguin',
    englishName: 'Galapagos penguin',
    latinName: 'Spheniscus mendiculus',
    category: 'Animal',
    roleDefault: 'specimen',
    collisionRadius: 0.52,
    interactionHeight: 0.56,
    carry: { label: 'penguin', holdHeight: 0.95 },
    behavior: {
      controller: 'ground',
      habitatRadiusX: 6.2,
      habitatRadiusZ: 3.4,
      walkSpeed: 0.26,
      fleeSpeed: 1.25,
      patrolRate: 0.34,
      alertRadius: 4.6,
      panicRadius: 1.3,
      hammerAlertRadius: 7.5,
      bobAmount: 0.02,
      groundOffset: 0.04,
      turnRate: 9,
      idleClip: 'MoverPinguino|Take 001|BaseLayer',
      walkClip: 'MoverPinguino|Take 001|BaseLayer',
      runClip: 'MoverPinguino|Take 001|BaseLayer',
      movementStyle: 'waddle',
      contactReaction: 'waddle-away',
      contactAlertRadius: 3.4,
      contactReactionDuration: 1.25,
      startleDuration: 0.72,
      startleSpeedMultiplier: 0.7,
      startleCooldown: 3.0,
    },
  },
  floreanagianttortoise: {
    id: 'floreanagianttortoise',
    assetId: 'floreanaGiantTortoise',
    englishName: 'Floreana giant tortoise',
    latinName: 'Chelonoidis niger niger',
    category: 'Animal',
    roleDefault: 'specimen',
    collisionRadius: 1.25,
    interactionHeight: 1.05,
    carry: { label: 'tortoise', holdHeight: 0.7 },
    behavior: {
      controller: 'ground',
      habitatRadiusX: 4.6,
      habitatRadiusZ: 2.6,
      walkSpeed: 0.08,
      fleeSpeed: 0.44,
      patrolRate: 0.18,
      alertRadius: 3.2,
      panicRadius: 0.95,
      hammerAlertRadius: 5.5,
      bobAmount: 0.002,
      groundOffset: 0.04,
      turnRate: 5,
      movementStyle: 'heavy',
      contactReaction: 'slow-withdraw',
      contactAlertRadius: 3.4,
      contactReactionDuration: 3.0,
      contactFleeMultiplier: 2.25,
      startleDuration: 0.8,
      startleSpeedMultiplier: 0.45,
      startleCooldown: 4.5,
    },
  },
  crab: {
    id: 'crab',
    assetId: 'crab',
    englishName: 'Sally Lightfoot crab',
    latinName: 'Grapsus grapsus',
    category: 'Animal',
    roleDefault: 'ambient',
    collisionRadius: 0.54,
    interactionHeight: 0.18,
    behavior: {
      controller: 'ground',
      habitatRadiusX: 5.8,
      habitatRadiusZ: 2.8,
      walkSpeed: 0.55,
      fleeSpeed: 2.25,
      patrolRate: 0.55,
      alertRadius: 5.2,
      panicRadius: 1.55,
      bobAmount: 0.018,
      groundOffset: 0.04,
      turnRate: 14,
      idleClip: 'Armature|CrabAll_Eat',
      feedClip: 'Armature|CrabAll_Eat',
      walkClip: 'Armature|CrabAll_Walk',
      runClip: 'Armature|CrabAll_Strafe',
      movementStyle: 'scuttle',
      movementFacingMode: 'sideways',
      contactReaction: 'sideways-scuttle',
      contactAlertRadius: 3.8,
      contactReactionDuration: 1.0,
      orbitSpeed: 0.9,
      orbitRadiusScaleX: 0.34,
      orbitRadiusScaleZ: 0.26,
      scuttleFrequency: 11,
      scuttleAmplitude: 0.22,
      startleDuration: 0.95,
      startleSpeedMultiplier: 1.15,
      startleCooldown: 2.4,
    },
  },
  cat: {
    id: 'cat',
    assetId: 'settlementCat',
    englishName: 'Settlement cat',
    latinName: 'Felis catus',
    category: 'Animal',
    roleDefault: 'specimen',
    collisionRadius: 0.42,
    interactionHeight: 0.36,
    behavior: {
      controller: 'ground',
      habitatRadiusX: 4.8,
      habitatRadiusZ: 2.8,
      walkSpeed: 0.2,
      fleeSpeed: 2.15,
      patrolRate: 0.22,
      alertRadius: 4.8,
      panicRadius: 1.15,
      bobAmount: 0.006,
      groundOffset: 0.035,
      turnRate: 12,
      idleClip: 'Armature|Cat-ALL_IdlePurr',
      feedClip: 'Armature|Cat-ALL_LickCleanIdle',
      restClip: 'Armature|Cat-ALL_StretchYawnIdle',
      walkClip: 'Armature|Cat-ALL_Walk',
      runClip: 'Armature|Cat-ALL_Walk',
      movementStyle: 'stalk',
      facingYawOffset: -Math.PI / 2,
      contactReaction: 'dart-away',
      contactAlertRadius: 3.4,
      contactReactionDuration: 1.0,
      contactFleeMultiplier: 1.35,
      orbitSpeed: 0.18,
      orbitRadiusScaleX: 0.32,
      orbitRadiusScaleZ: 0.24,
      startleDuration: 0.85,
      startleSpeedMultiplier: 0.9,
      startleCooldown: 3.6,
      idleVariantRate: 0.13,
    },
  },
  feralgoat: {
    id: 'feralgoat',
    assetId: 'feralGoat',
    englishName: 'Feral goat',
    latinName: 'Capra hircus feralis',
    category: 'Animal',
    roleDefault: 'specimen',
    collisionRadius: 0.62,
    interactionHeight: 0.88,
    behavior: {
      controller: 'grazer',
      habitatRadiusX: 9.0,
      habitatRadiusZ: 5.5,
      walkSpeed: 0.24,
      trotSpeed: 0.56,
      fleeSpeed: 1.85,
      patrolRate: 0.2,
      alertRadius: 7.2,
      panicRadius: 2.2,
      hammerAlertRadius: 9.0,
      bobAmount: 0.012,
      groundOffset: 0.055,
      turnRate: 8,
      obstacleRadius: 0.62,
      obstacleStepTolerance: 0.18,
      reach: 0.22,
      idleClip: 'Armature|Armature|idle',
      feedClip: 'Armature|Armature|idle2',
      restClip: 'Armature|Armature|laydown',
      sleepClip: 'Armature|Armature|sleep',
      wakeClip: 'Armature|Armature|wake up',
      walkClip: 'Armature|Armature|walk',
      trotClip: 'Armature|Armature|trot',
      runClip: 'Armature|Armature|run',
      ramRunClip: 'Armature|Armature|ram run',
      kickClip: 'Armature|Armature|rear kick',
      woundClip: 'Armature|Armature|wound',
      movementStyle: 'grazer',
      contactReaction: 'bolt-away',
      contactAlertRadius: 4.6,
      contactReactionDuration: 1.1,
      contactFleeMultiplier: 1.25,
      fleeHabitatScale: 1.42,
      startleRadius: 6.2,
      startleDuration: 0.9,
      startleSpeedMultiplier: 0.85,
      startleCooldown: 3.2,
      idleVariantRate: 0.1,
      kickRadius: 1.2,
      wakeLeadTime: 3.7,
    },
  },
  feralhorse: {
    id: 'feralhorse',
    assetId: 'feralHorse',
    englishName: 'Feral horse',
    latinName: 'Equus ferus caballus',
    category: 'Animal',
    roleDefault: 'specimen',
    collisionRadius: 1.25,
    interactionHeight: 1.65,
    behavior: {
      controller: 'grazer',
      habitatRadiusX: 13.0,
      habitatRadiusZ: 7.0,
      walkSpeed: 0.34,
      fleeSpeed: 2.45,
      patrolRate: 0.16,
      alertRadius: 9.2,
      panicRadius: 3.0,
      hammerAlertRadius: 11.0,
      bobAmount: 0.008,
      groundOffset: 0.055,
      turnRate: 6.8,
      obstacleRadius: 1.18,
      obstacleStepTolerance: 0.24,
      reach: 0.34,
      idleClip: 'Armature|HorseALL_Idle',
      idleClips: [
        'Armature|HorseALL_SlowIdle',
        'Armature|HorseALL_Idle3',
        'Armature|HorseALL_IdleEars',
        'Armature|HorseALL_Restless',
        'Armature|HorseALL_Restless2',
        'Armature|HorseALL_Restless3',
      ],
      feedClip: 'Armature|HorseALL_HoofScrape',
      feedClips: [
        'Armature|HorseALL_HoofScrape2',
        'Armature|HorseALL_SlowIdle',
        'Armature|HorseALL_Restless',
      ],
      restClip: 'Armature|HorseALL_Lying',
      sleepClip: 'Armature|HorseALL_Lying',
      wakeClip: 'Armature|HorseALL_GetUp',
      walkClip: 'Armature|HorseALL_SlowWalk',
      runClip: 'Armature|HorseALL_RunLoop',
      ramRunClip: 'Armature|HorseALL_RunLoop',
      kickClip: 'Armature|HorseALL_Rearing',
      kickClips: [
        'Armature|HorseALL_Rearing2',
        'Armature|HorseALL_Bucking',
        'Armature|HorseALL_FeetUp',
        'Armature|HorseALL_Attack',
      ],
      woundClip: 'Armature|HorseALL_KnockedBack',
      alertClip: 'Armature|HorseALL_Restless3',
      movementStyle: 'grazer',
      facingYawOffset: -Math.PI / 2,
      contactReaction: 'bolt-away',
      contactAlertRadius: 6.4,
      contactReactionDuration: 1.2,
      contactFleeMultiplier: 1.2,
      fleeHabitatScale: 1.34,
      startleRadius: 8.0,
      startleDuration: 1.0,
      startleSpeedMultiplier: 0.72,
      startleCooldown: 3.8,
      idleVariantRate: 0.08,
      kickRadius: 1.85,
      wakeLeadTime: 1.4,
    },
  },
  jackothemonkey: {
    id: 'jackothemonkey',
    assetId: 'jackoMonkey',
    englishName: 'Jacko the Monkey',
    latinName: 'Cebus marinus',
    category: 'Animal',
    roleDefault: 'specimen',
    collisionRadius: 0.48,
    interactionHeight: 0.58,
    behavior: {
      controller: 'deckMonkey',
      habitatRadiusX: 7.2,
      habitatRadiusZ: 4.0,
      walkSpeed: 0.28,
      fleeSpeed: 0.95,
      climbSpeed: 0.55,
      patrolRate: 0.42,
      alertRadius: 3.2,
      panicRadius: 1.15,
      hammerAlertRadius: 5.5,
      bobAmount: 0.01,
      groundOffset: 0.08,
      turnRate: 9,
      facingYawOffset: Math.PI,
      strictSurfaceRoute: true,
      obstacleRadius: 0.5,
      obstaclePause: 0.95,
      obstacleRetargetCooldown: 0.7,
      idleClip: 'Armature|MonkeyAll_Idle1',
      feedClip: 'Armature|MonkeyAll_Idle2',
      restClip: 'Armature|MonkeyAll_B1Idle',
      teaseClip: 'Armature|MonkeyAll_Monkeyb1',
      alertClip: 'Armature|MonkeyAll_Attack2',
      walkClip: 'Armature|MonkeyAll_Walk',
      runClip: 'Armature|MonkeyAll_Run',
      climbClip: 'Armature|MonkeyAll_Run',
      movementStyle: 'scamper',
      contactReaction: 'scramble-to-rigging',
      contactAlertRadius: 4.8,
      contactReactionDuration: 1.25,
      contactFleeMultiplier: 1.35,
      startleRadius: 3.0,
      startleDuration: 0.5,
      startleSpeedMultiplier: 0.45,
      startleCooldown: 4.8,
      idleVariantRate: 0.1,
      deckWaypoints: [
        { x: 4.8, z: -1.25, yOffset: 0.08, mode: 'deck', wait: 7.5 },
        { x: 5.55, z: -1.35, yOffset: 0.08, mode: 'npc-tease', wait: 8.0 },
        { x: 7.1, z: -1.35, yOffset: 0.08, mode: 'deck', wait: 5.8 },
        { x: 8.8, z: 0.9, yOffset: 0.08, mode: 'deck', wait: 8.4 },
        { x: 6.4, z: 1.45, yOffset: 0.08, mode: 'deck', wait: 6.2 },
        { x: 2.2, z: 1.15, yOffset: 0.08, mode: 'deck', wait: 7.0 },
        { x: -0.8, z: -1.45, yOffset: 0.08, mode: 'deck', wait: 6.6 },
        { x: -4.6, z: -1.25, yOffset: 0.08, mode: 'deck', wait: 7.8 },
        { x: -6.2, z: 1.25, yOffset: 0.08, mode: 'deck', wait: 8.8 },
        { x: -4.6, z: 1.75, yOffset: 0.08, mode: 'deck', wait: 7.2 },
        { x: -1.1, z: 1.55, yOffset: 0.08, mode: 'deck', wait: 7.6 },
        { x: -0.8, z: -1.45, yOffset: 0.08, mode: 'deck', wait: 6.4 },
        { x: 2.2, z: 1.15, yOffset: 0.08, mode: 'deck', wait: 7.0 },
      ],
      escapeWaypointModes: ['deck'],
      deckNpcPositions: [
        { id: 'syms', x: 5.4, z: -1.9, radius: 2.2 },
        { id: 'fitzroy', x: -18.0, z: 0.6, radius: 2.6 },
        { id: 'lascar_joe', x: 9.6, z: 2.1, radius: 2.4 },
      ],
    },
  },
  flightlesscormorant: {
    id: 'flightlesscormorant',
    assetId: 'flightlessCormorant',
    englishName: 'Flightless cormorant',
    latinName: 'Nannopterum harrisi',
    category: 'Animal',
    roleDefault: 'specimen',
    collisionRadius: 0.74,
    interactionHeight: 0.78,
    behavior: {
      controller: 'ground',
      habitatRadiusX: 8.5,
      habitatRadiusZ: 4.2,
      walkSpeed: 0.42,
      fleeSpeed: 1.15,
      patrolRate: 0.32,
      alertRadius: 6.0,
      panicRadius: 1.8,
      bobAmount: 0.025,
      groundOffset: 0.04,
      turnRate: 7,
      walkClip: 'walk',
      runClip: 'walk',
      movementStyle: 'waddle',
      contactReaction: 'brisk-walk-away',
      contactAlertRadius: 4.2,
      contactReactionDuration: 1.35,
      orbitSpeed: 0.22,
      orbitRadiusScaleX: 0.34,
      orbitRadiusScaleZ: 0.28,
      startleDuration: 0.65,
      startleSpeedMultiplier: 0.5,
      startleCooldown: 3.4,
    },
  },
  frigatebird: {
    id: 'frigatebird',
    assetId: 'frigatebird',
    englishName: 'Magnificent frigatebird',
    latinName: 'Fregata magnificens',
    category: 'Animal',
    roleDefault: 'specimen',
    collisionRadius: 0.66,
    interactionHeight: 0.78,
    behavior: {
      controller: 'ground',
      habitatRadiusX: 10.5,
      habitatRadiusZ: 4.8,
      walkSpeed: 0.46,
      fleeSpeed: 2.85,
      patrolRate: 0.42,
      alertRadius: 8.5,
      panicRadius: 2.25,
      bobAmount: 0.018,
      groundOffset: 0.05,
      turnRate: 13,
      walkClip: 'walk',
      runClip: 'run',
      movementStyle: 'waddle',
      contactReaction: 'fast-walk-away',
      contactAlertRadius: 5.2,
      contactReactionDuration: 1.4,
      orbitSpeed: 0.24,
      orbitRadiusScaleX: 0.32,
      orbitRadiusScaleZ: 0.24,
      startleDuration: 0.7,
      startleSpeedMultiplier: 0.75,
      startleCooldown: 3.0,
    },
  },
  booby: {
    id: 'booby',
    assetId: 'blueFootedBooby',
    englishName: 'Blue-footed booby',
    latinName: 'Sula nebouxii',
    category: 'Animal',
    roleDefault: 'specimen',
    collisionRadius: 0.62,
    interactionHeight: 0.72,
    behavior: {
      controller: 'ground',
      habitatRadiusX: 8.2,
      habitatRadiusZ: 4.2,
      walkSpeed: 0.34,
      fleeSpeed: 1.85,
      patrolRate: 0.36,
      alertRadius: 6.2,
      panicRadius: 1.7,
      bobAmount: 0.018,
      groundOffset: 0.05,
      turnRate: 8,
      idleClip: 'idle',
      walkClip: 'walk',
      runClip: 'run',
      movementStyle: 'waddle',
      contactReaction: 'fast-walk-away',
      contactAlertRadius: 4.6,
      contactReactionDuration: 1.35,
      orbitSpeed: 0.24,
      orbitRadiusScaleX: 0.34,
      orbitRadiusScaleZ: 0.26,
      startleDuration: 0.72,
      startleSpeedMultiplier: 0.65,
      startleCooldown: 3.1,
    },
  },
  flamingo: {
    id: 'flamingo',
    assetId: 'flamingoAnimated',
    englishName: 'American flamingo',
    latinName: 'Phoenicopterus ruber',
    category: 'Animal',
    roleDefault: 'specimen',
    collisionRadius: 0.5,
    interactionHeight: 1.35,
    behavior: {
      controller: 'ground',
      habitatRadiusX: 5.2,
      habitatRadiusZ: 2.6,
      walkSpeed: 0.12,
      fleeSpeed: 0.42,
      patrolRate: 0.16,
      alertRadius: 4.4,
      panicRadius: 1.35,
      bobAmount: 0.004,
      groundOffset: 0.02,
      turnRate: 3.2,
      idleClip: 'Armature|Flamingo-ALL_BendIdle',
      feedClip: 'Armature|Flamingo-ALL_BendIdle',
      restClip: 'Armature|Flamingo-ALL_OneLEgBEnt',
      sleepClip: 'Armature|Flamingo-ALL_Sleep',
      walkClip: 'Armature|Flamingo-ALL_Walk',
      runClip: 'Armature|Flamingo-ALL_Walk',
      movementStyle: 'wade',
      contactReaction: 'slow-wade-away',
      contactAlertRadius: 3.2,
      contactReactionDuration: 1.8,
      contactFleeMultiplier: 1.25,
      orbitSpeed: 0.13,
      orbitRadiusScaleX: 0.28,
      orbitRadiusScaleZ: 0.2,
      startleDuration: 0.9,
      startleSpeedMultiplier: 0.35,
      startleCooldown: 4.5,
      idleVariantRate: 0.11,
    },
  },
  lavagull: {
    id: 'lavagull',
    assetId: 'seagull',
    englishName: 'Lava gull',
    latinName: 'Leucophaeus fuliginosus',
    category: 'Animal',
    roleDefault: 'specimen',
    collisionRadius: 0.42,
    interactionHeight: 0.34,
    behavior: {
      controller: 'shorebird',
      habitatRadiusX: 10.5,
      habitatRadiusZ: 5.2,
      walkSpeed: 0.28,
      fleeSpeed: 1.55,
      patrolRate: 0.24,
      alertRadius: 7.2,
      panicRadius: 2.15,
      bobAmount: 0.012,
      groundOffset: 0.055,
      turnRate: 12,
      idleClip: 'Armature|look',
      feedClip: 'Armature|eat',
      preenClip: 'Armature|clearing',
      walkClip: 'Armature|walk',
      runClip: 'Armature|run',
      flyClip: 'Armature|fly',
      glideClip: 'Armature|glide',
      contactReaction: 'takeoff',
      contactAlertRadius: 4.8,
      contactReactionDuration: 1.25,
      startleDuration: 1.05,
      startleSpeedMultiplier: 0.55,
      startleCooldown: 3.4,
      takeoffRadius: 3.7,
      takeoffDuration: 1.45,
      flightDuration: 10.5,
      flightHeight: 4.4,
      flightRadiusX: 7.2,
      flightRadiusZ: 3.7,
      landingDuration: 1.8,
      landClearRadius: 5.6,
      orbitSpeed: 0.54,
      rollAmount: 0.11,
      pitchAmount: 0.055,
    },
  },
  lavalizard: {
    id: 'lavalizard',
    assetId: 'lavalizard',
    englishName: 'Floreana lava lizard',
    latinName: 'Microlophus grayii',
    category: 'Animal',
    roleDefault: 'specimen',
    collisionRadius: 0.34,
    interactionHeight: 0.25,
    behavior: {
      controller: 'ground',
      habitatRadiusX: 3.2,
      habitatRadiusZ: 1.6,
      walkSpeed: 0.26,
      fleeSpeed: 2.1,
      patrolRate: 0.7,
      alertRadius: 4.2,
      panicRadius: 1.2,
      bobAmount: 0.008,
      groundOffset: 0.04,
      turnRate: 16,
      idleClip: 'Idle',
      walkClip: 'Walk',
      runClip: 'Walk',
      movementStyle: 'dart',
      contactReaction: 'dart-away',
      contactAlertRadius: 3.8,
      contactReactionDuration: 0.9,
      orbitSpeed: 0.7,
      orbitRadiusScaleX: 0.36,
      orbitRadiusScaleZ: 0.28,
      startleDuration: 0.8,
      startleSpeedMultiplier: 1.25,
      startleCooldown: 2.2,
    },
  },
  greenturtle: {
    id: 'greenturtle',
    assetId: 'greenTurtle',
    englishName: 'Sea turtle',
    latinName: 'Cheloniidae',
    category: 'Animal',
    roleDefault: 'specimen',
    collisionRadius: 0.72,
    interactionHeight: 0.42,
  },
  sealion: {
    id: 'sealion',
    assetId: 'seaLion',
    englishName: 'Galapagos sea lion',
    latinName: 'Zalophus wollebaeki',
    category: 'Animal',
    roleDefault: 'specimen',
    collisionRadius: 0.95,
    interactionHeight: 0.82,
  },
};

export const wildlifeBehaviorProfiles = Object.fromEntries(
  Object.entries(wildlifeCatalog)
    .filter(([, entry]) => entry.behavior)
    .map(([id, entry]) => [id, { ...entry.behavior }]),
);

export const wildlifeCarryProfiles = Object.fromEntries(
  Object.entries(wildlifeCatalog)
    .filter(([, entry]) => entry.carry)
    .map(([id, entry]) => [id, { ...entry.carry }]),
);

export function getWildlifeSpecies(input) {
  return wildlifeCatalog[normalizeWildlifeId(input)] || null;
}

export function getWildlifeBehaviorProfile(input) {
  const entry = getWildlifeSpecies(input);
  return entry?.behavior || null;
}

export function getWildlifeCarryProfile(input) {
  return getWildlifeSpecies(input)?.carry || null;
}

export function getWildlifeAssetId(input) {
  return getWildlifeSpecies(input)?.assetId || null;
}

export function getWildlifeCollisionRadius(input) {
  return getWildlifeSpecies(input)?.collisionRadius ?? null;
}

export function getWildlifeInteractionHeight(input) {
  return getWildlifeSpecies(input)?.interactionHeight ?? null;
}

export function createAmbientWildlifeSpecimen(item) {
  const speciesId = normalizeWildlifeId(item?.speciesId || item?.species || item?.specimenId || item?.id);
  const entry = wildlifeCatalog[speciesId];
  if (!entry) return null;
  const position = item.position || item.spawnPoint || [0, 0, 0];
  return {
    id: speciesId,
    specimenId: speciesId,
    instanceId: item.instanceId || item.id || `${speciesId}-ambient`,
    name: item.name || entry.englishName,
    latin: item.latin || entry.latinName,
    ontology: item.ontology || entry.category || 'Animal',
    spawnPoint: position,
    behavior: item.behavior || 'ambient',
    sceneScale: Number.isFinite(item.sceneScale) ? item.sceneScale : 1,
    habitatRadiusX: item.habitatRadiusX ?? entry.behavior?.habitatRadiusX,
    habitatRadiusZ: item.habitatRadiusZ ?? entry.behavior?.habitatRadiusZ,
    role: item.role || 'ambient',
  };
}
