const SPECIES_ALIASES = {
  bluefootedbooby: 'booby',
  blue_footed_booby: 'booby',
  floreana_giant_tortoise: 'floreanagianttortoise',
  floreanagianttortoise: 'floreanagianttortoise',
  greenTurtle: 'greenturtle',
  green_turtle: 'greenturtle',
  marineIguana: 'marineiguana',
  marine_iguana: 'marineiguana',
  mediumGroundFinch: 'mediumgroundfinch',
  medium_ground_finch: 'mediumgroundfinch',
  seaLion: 'sealion',
  sea_lion: 'sealion',
};

export function normalizeWildlifeId(input) {
  const raw = typeof input === 'string' ? input : input?.id || input?.specimenId || '';
  if (!raw) return '';
  const compact = String(raw).replace(/[^a-zA-Z0-9_]/g, '').toLowerCase();
  return SPECIES_ALIASES[raw] || SPECIES_ALIASES[compact] || compact;
}

export const wildlifeCatalog = {
  mediumgroundfinch: {
    id: 'mediumgroundfinch',
    assetId: 'mediumGroundFinch',
    englishName: 'Medium ground finch',
    latinName: 'Geospiza fortis',
    category: 'Animal',
    roleDefault: 'specimen',
    collisionRadius: 0.28,
    interactionHeight: 0.2,
    behavior: {
      controller: 'ground',
      habitatRadiusX: 5.2,
      habitatRadiusZ: 3.2,
      walkSpeed: 0.32,
      fleeSpeed: 2.15,
      patrolRate: 0.62,
      alertRadius: 4.8,
      panicRadius: 1.25,
      hammerAlertRadius: 8.5,
      bobAmount: 0.028,
      groundOffset: 0.04,
      turnRate: 15,
      idleClip: 'headTilt',
      movementStyle: 'hop',
      contactReaction: 'quick-hop-away',
      contactAlertRadius: 3.6,
      contactReactionDuration: 1.1,
      startleDuration: 0.85,
      startleSpeedMultiplier: 0.95,
      startleCooldown: 2.8,
    },
  },
  marineiguana: {
    id: 'marineiguana',
    assetId: 'marineIguana',
    englishName: 'Marine iguana',
    latinName: 'Amblyrhynchus cristatus',
    category: 'Animal',
    roleDefault: 'specimen',
    collisionRadius: 0.58,
    interactionHeight: 0.25,
    carry: { label: 'marine iguana', holdHeight: 0.88 },
    behavior: {
      controller: 'ground',
      habitatRadiusX: 6.8,
      habitatRadiusZ: 3.6,
      walkSpeed: 0.22,
      fleeSpeed: 1.45,
      patrolRate: 0.38,
      alertRadius: 4.8,
      panicRadius: 1.35,
      hammerAlertRadius: 8.0,
      bobAmount: 0.006,
      groundOffset: 0.04,
      turnRate: 10,
      idleClip: 'Iguana|Iguana|IguanaAction',
      walkClip: 'Iguana|Iguana|IguanaAction',
      runClip: 'Iguana|Iguana|IguanaAction',
      movementStyle: 'crawl',
      contactReaction: 'shuffle-away',
      contactAlertRadius: 3.2,
      contactReactionDuration: 1.2,
      orbitSpeed: 0.18,
      orbitRadiusScaleX: 0.28,
      orbitRadiusScaleZ: 0.22,
      startleDuration: 0.75,
      startleSpeedMultiplier: 0.65,
      startleCooldown: 3.1,
    },
  },
  galapagospenguin: {
    id: 'galapagospenguin',
    assetId: 'galapagosPenguin',
    englishName: 'Galapagos penguin',
    latinName: 'Spheniscus mendiculus',
    category: 'Animal',
    roleDefault: 'specimen',
    collisionRadius: 0.52,
    interactionHeight: 0.56,
    carry: { label: 'penguin', holdHeight: 0.95 },
    behavior: {
      controller: 'ground',
      habitatRadiusX: 6.2,
      habitatRadiusZ: 3.4,
      walkSpeed: 0.26,
      fleeSpeed: 1.25,
      patrolRate: 0.34,
      alertRadius: 4.6,
      panicRadius: 1.3,
      hammerAlertRadius: 7.5,
      bobAmount: 0.02,
      groundOffset: 0.04,
      turnRate: 9,
      idleClip: 'MoverPinguino|Take 001|BaseLayer',
      walkClip: 'MoverPinguino|Take 001|BaseLayer',
      runClip: 'MoverPinguino|Take 001|BaseLayer',
      movementStyle: 'waddle',
      contactReaction: 'waddle-away',
      contactAlertRadius: 3.4,
      contactReactionDuration: 1.25,
      startleDuration: 0.72,
      startleSpeedMultiplier: 0.7,
      startleCooldown: 3.0,
    },
  },
  floreanagianttortoise: {
    id: 'floreanagianttortoise',
    assetId: 'floreanaGiantTortoise',
    englishName: 'Floreana giant tortoise',
    latinName: 'Chelonoidis niger niger',
    category: 'Animal',
    roleDefault: 'specimen',
    collisionRadius: 1.25,
    interactionHeight: 1.05,
    carry: { label: 'tortoise', holdHeight: 0.7 },
    behavior: {
      controller: 'ground',
      habitatRadiusX: 4.6,
      habitatRadiusZ: 2.6,
      walkSpeed: 0.08,
      fleeSpeed: 0.44,
      patrolRate: 0.18,
      alertRadius: 3.2,
      panicRadius: 0.95,
      hammerAlertRadius: 5.5,
      bobAmount: 0.002,
      groundOffset: 0.04,
      turnRate: 5,
      movementStyle: 'heavy',
      contactReaction: 'slow-withdraw',
      contactAlertRadius: 3.4,
      contactReactionDuration: 3.0,
      contactFleeMultiplier: 2.25,
      startleDuration: 0.8,
      startleSpeedMultiplier: 0.45,
      startleCooldown: 4.5,
    },
  },
  crab: {
    id: 'crab',
    assetId: 'crab',
    englishName: 'Sally Lightfoot crab',
    latinName: 'Grapsus grapsus',
    category: 'Animal',
    roleDefault: 'ambient',
    collisionRadius: 0.54,
    interactionHeight: 0.18,
    behavior: {
      controller: 'ground',
      habitatRadiusX: 5.8,
      habitatRadiusZ: 2.8,
      walkSpeed: 0.55,
      fleeSpeed: 2.25,
      patrolRate: 0.55,
      alertRadius: 5.2,
      panicRadius: 1.55,
      bobAmount: 0.018,
      groundOffset: 0.04,
      turnRate: 14,
      movementStyle: 'scuttle',
      movementFacingMode: 'sideways',
      contactReaction: 'sideways-scuttle',
      contactAlertRadius: 3.8,
      contactReactionDuration: 1.0,
      orbitSpeed: 0.9,
      orbitRadiusScaleX: 0.34,
      orbitRadiusScaleZ: 0.26,
      scuttleFrequency: 11,
      scuttleAmplitude: 0.22,
      startleDuration: 0.95,
      startleSpeedMultiplier: 1.15,
      startleCooldown: 2.4,
    },
  },
  flightlesscormorant: {
    id: 'flightlesscormorant',
    assetId: 'flightlessCormorant',
    englishName: 'Flightless cormorant',
    latinName: 'Nannopterum harrisi',
    category: 'Animal',
    roleDefault: 'specimen',
    collisionRadius: 0.74,
    interactionHeight: 0.78,
    behavior: {
      controller: 'ground',
      habitatRadiusX: 8.5,
      habitatRadiusZ: 4.2,
      walkSpeed: 0.42,
      fleeSpeed: 1.15,
      patrolRate: 0.32,
      alertRadius: 6.0,
      panicRadius: 1.8,
      bobAmount: 0.025,
      groundOffset: 0.04,
      turnRate: 7,
      walkClip: 'walk',
      runClip: 'walk',
      movementStyle: 'waddle',
      contactReaction: 'brisk-walk-away',
      contactAlertRadius: 4.2,
      contactReactionDuration: 1.35,
      orbitSpeed: 0.22,
      orbitRadiusScaleX: 0.34,
      orbitRadiusScaleZ: 0.28,
      startleDuration: 0.65,
      startleSpeedMultiplier: 0.5,
      startleCooldown: 3.4,
    },
  },
  frigatebird: {
    id: 'frigatebird',
    assetId: 'frigatebird',
    englishName: 'Magnificent frigatebird',
    latinName: 'Fregata magnificens',
    category: 'Animal',
    roleDefault: 'specimen',
    collisionRadius: 0.66,
    interactionHeight: 0.78,
    behavior: {
      controller: 'ground',
      habitatRadiusX: 10.5,
      habitatRadiusZ: 4.8,
      walkSpeed: 0.46,
      fleeSpeed: 2.85,
      patrolRate: 0.42,
      alertRadius: 8.5,
      panicRadius: 2.25,
      bobAmount: 0.018,
      groundOffset: 0.05,
      turnRate: 13,
      walkClip: 'walk',
      runClip: 'run',
      movementStyle: 'waddle',
      contactReaction: 'fast-walk-away',
      contactAlertRadius: 5.2,
      contactReactionDuration: 1.4,
      orbitSpeed: 0.24,
      orbitRadiusScaleX: 0.32,
      orbitRadiusScaleZ: 0.24,
      startleDuration: 0.7,
      startleSpeedMultiplier: 0.75,
      startleCooldown: 3.0,
    },
  },
  booby: {
    id: 'booby',
    assetId: 'blueFootedBooby',
    englishName: 'Blue-footed booby',
    latinName: 'Sula nebouxii',
    category: 'Animal',
    roleDefault: 'specimen',
    collisionRadius: 0.62,
    interactionHeight: 0.72,
    behavior: {
      controller: 'ground',
      habitatRadiusX: 8.2,
      habitatRadiusZ: 4.2,
      walkSpeed: 0.34,
      fleeSpeed: 1.85,
      patrolRate: 0.36,
      alertRadius: 6.2,
      panicRadius: 1.7,
      bobAmount: 0.018,
      groundOffset: 0.05,
      turnRate: 8,
      idleClip: 'idle',
      walkClip: 'walk',
      runClip: 'run',
      movementStyle: 'waddle',
      contactReaction: 'fast-walk-away',
      contactAlertRadius: 4.6,
      contactReactionDuration: 1.35,
      orbitSpeed: 0.24,
      orbitRadiusScaleX: 0.34,
      orbitRadiusScaleZ: 0.26,
      startleDuration: 0.72,
      startleSpeedMultiplier: 0.65,
      startleCooldown: 3.1,
    },
  },
  lavalizard: {
    id: 'lavalizard',
    assetId: 'lavalizard',
    englishName: 'Floreana lava lizard',
    latinName: 'Microlophus grayii',
    category: 'Animal',
    roleDefault: 'specimen',
    collisionRadius: 0.34,
    interactionHeight: 0.25,
    behavior: {
      controller: 'ground',
      habitatRadiusX: 3.2,
      habitatRadiusZ: 1.6,
      walkSpeed: 0.35,
      fleeSpeed: 2.6,
      patrolRate: 0.7,
      alertRadius: 4.2,
      panicRadius: 1.2,
      bobAmount: 0.008,
      groundOffset: 0.04,
      turnRate: 16,
      idleClip: 'Idle',
      walkClip: 'Walk',
      runClip: 'Walk',
      movementStyle: 'dart',
      contactReaction: 'dart-away',
      contactAlertRadius: 3.8,
      contactReactionDuration: 0.9,
      orbitSpeed: 0.82,
      orbitRadiusScaleX: 0.36,
      orbitRadiusScaleZ: 0.28,
      startleDuration: 0.8,
      startleSpeedMultiplier: 1.25,
      startleCooldown: 2.2,
    },
  },
  greenturtle: {
    id: 'greenturtle',
    assetId: 'greenTurtle',
    englishName: 'Sea turtle',
    latinName: 'Cheloniidae',
    category: 'Animal',
    roleDefault: 'specimen',
    collisionRadius: 0.72,
    interactionHeight: 0.42,
  },
  sealion: {
    id: 'sealion',
    assetId: 'seaLion',
    englishName: 'Galapagos sea lion',
    latinName: 'Zalophus wollebaeki',
    category: 'Animal',
    roleDefault: 'specimen',
    collisionRadius: 0.95,
    interactionHeight: 0.82,
  },
};

export const wildlifeBehaviorProfiles = Object.fromEntries(
  Object.entries(wildlifeCatalog)
    .filter(([, entry]) => entry.behavior?.controller === 'ground')
    .map(([id, entry]) => [id, { ...entry.behavior }]),
);

export const wildlifeCarryProfiles = Object.fromEntries(
  Object.entries(wildlifeCatalog)
    .filter(([, entry]) => entry.carry)
    .map(([id, entry]) => [id, { ...entry.carry }]),
);

export function getWildlifeSpecies(input) {
  return wildlifeCatalog[normalizeWildlifeId(input)] || null;
}

export function getWildlifeBehaviorProfile(input) {
  const entry = getWildlifeSpecies(input);
  return entry?.behavior?.controller === 'ground' ? entry.behavior : null;
}

export function getWildlifeCarryProfile(input) {
  return getWildlifeSpecies(input)?.carry || null;
}

export function getWildlifeAssetId(input) {
  return getWildlifeSpecies(input)?.assetId || null;
}

export function getWildlifeCollisionRadius(input) {
  return getWildlifeSpecies(input)?.collisionRadius ?? null;
}

export function getWildlifeInteractionHeight(input) {
  return getWildlifeSpecies(input)?.interactionHeight ?? null;
}

export function createAmbientWildlifeSpecimen(item) {
  const speciesId = normalizeWildlifeId(item?.speciesId || item?.species || item?.specimenId || item?.id);
  const entry = wildlifeCatalog[speciesId];
  if (!entry) return null;
  const position = item.position || item.spawnPoint || [0, 0, 0];
  return {
    id: speciesId,
    specimenId: speciesId,
    instanceId: item.instanceId || item.id || `${speciesId}-ambient`,
    name: item.name || entry.englishName,
    latin: item.latin || entry.latinName,
    ontology: item.ontology || entry.category || 'Animal',
    spawnPoint: position,
    behavior: item.behavior || 'ambient',
    sceneScale: Number.isFinite(item.sceneScale) ? item.sceneScale : 1,
    habitatRadiusX: item.habitatRadiusX ?? entry.behavior?.habitatRadiusX,
    habitatRadiusZ: item.habitatRadiusZ ?? entry.behavior?.habitatRadiusZ,
    role: item.role || 'ambient',
  };
}
