export const modelAssets = {
  darwin: {
    enabled: true,
    preload: true,
    path: '/assets/models/darwin-final-animated.glb',
    // Runtime traversal clips are consolidated into the primary GLB so the
    // player does not parse the larger candidate animation library at startup.
    // Keep candidate2 below for hotkey-9 visual A/B testing.
    scale: 1.56,
    rotation: [0, 0, 0],
    yOffset: 0,
    visualGrounding: true,
    normalizeMaterials: true,
    materialLift: 0.1,
    materialEmissive: '#20170f',
    materialEmissiveIntensity: 0.16,
    // Player-only material polish layered on top of the cel pipeline: a subtle
    // fresnel rim for silhouette readability plus world tone mapping so Darwin
    // sits in the scene instead of reading as separately lit.
    // Tunables — ask for a screenshot to dial in. Remove to revert.
    materialUpgrade: { rimColor: '#ffdca8', rimPower: 4.2, rimIntensity: 0.11, roughness: 0.74, toneMapped: true },
    targetTriangles: 12000,
    prompt: 'Stylized low-poly young Charles Darwin naturalist, 1835 Galapagos expedition, wide-brim straw hat, brown frock coat, waistcoat, specimen satchel, field notebook, historically grounded, readable silhouette, hand-painted texture, cel-shaded game asset, neutral A-pose, clean topology, GLB.',
  },
  darwinCandidate2: {
    enabled: true,
    preload: false,
    path: '/assets/models/darwin-candidate-2-animated.glb',
    scale: 1,
    rotation: [0, 0, 0],
    yOffset: 0,
    visualGrounding: true,
    normalizeMaterials: true,
    materialLift: 0.08,
    materialEmissive: '#20170f',
    materialEmissiveIntensity: 0.14,
    // Same player rim/sheen as V1 so the hotkey-9 A/B isolates mesh+texture,
    // not a separate player-lighting treatment.
    materialUpgrade: { rimColor: '#ffdca8', rimPower: 4.2, rimIntensity: 0.11, roughness: 0.74, toneMapped: true },
    targetTriangles: 50000,
    prompt: 'Mixamo-rigged Young Darwin candidate 2 with expanded locomotion, traversal, injured, water, and naturalist action animation set.',
  },
  darwinTripo: {
    enabled: true,
    preload: false,
    // ?v bust: the GLB was rebuilt in place (UV fix); bump this if you rebuild
    // it again so the browser refetches instead of serving a stale cached copy.
    path: '/assets/models/darwin-tripo.glb',
    // Tripo v3.1 mesh, Mixamo-rigged (mixamorig:), decimated 1.96M -> 60k,
    // re-textured + regraded (scripts/regrade-tripo-texture.mjs) + WebP,
    // normalized to 1.75m. No baked clips — borrows V2's full set via
    // animationSource (identical skeleton; both ~1.75m so no track rescale).
    animationSource: 'darwinCandidate2',
    scale: 1.0,
    rotation: [0, 0, 0],
    yOffset: 0,
    visualGrounding: true,
    normalizeMaterials: true,
    // Tripo albedo is already warm/graded; no cream lift, softer emissive, and
    // a higher roughness + gentler rim so the (lighter) skin doesn't blow out.
    materialLift: 0,
    materialEmissive: '#20170f',
    materialEmissiveIntensity: 0.09,
    materialUpgrade: { rimColor: '#ffdca8', rimPower: 4.3, rimIntensity: 0.1, roughness: 0.88, toneMapped: true },
    targetTriangles: 60000,
    prompt: 'Tripo v3.1 Young Darwin, segmented + Mixamo-rigged, game-decimated.',
  },
  darwin4: {
    enabled: true,
    preload: false,
    path: '/assets/models/darwin4.glb',
    // Darwin 4: Mixamo-rigged FBX with embedded texture, rebuilt with native
    // baked clips retargeted onto its own 41-bone armature. Do not borrow V2
    // clips at runtime; that rig mismatch distorts proportions during gait.
    scale: 1.0,
    rotation: [0, 0, 0],
    yOffset: 0,
    visualGrounding: true,
    normalizeMaterials: true,
    materialLift: 0.025,
    materialEmissive: '#20170f',
    // Match darwin5: drop the self-lit emissive glow at night, lower roughness +
    // add envMap sheen so cloth/leather read as material, not flat "velvet".
    materialEmissiveIntensity: 0.035,
    // toneMapped:true — test running the player through ACES like the world. Flip
    // to false (or remove) to revert to the cel-pipeline un-tonemapped look.
    // Sidecar maps (scripts/build-darwin-roughness.mjs + build-darwin-detail.mjs):
    //  roughnessMapUrl — leather glossier + waistcoat semi-gloss, cloth/skin at 0.6.
    //  normalMapUrl    — gentle derived micro-detail relief (normalScale tunes it).
    //  albedoMapUrl    — crisper albedo + tamed hot cream trousers.
    // ?v bump busts the browser cache when a map is regenerated.
    materialUpgrade: { rimColor: '#ffdca8', rimPower: 4.4, rimIntensity: 0.12, roughness: 0.64, envMapIntensity: 0.24, toneMapped: true, roughnessMapUrl: '/assets/models/darwin4-roughness.webp?v=1', normalMapUrl: '/assets/models/darwin4-normal.webp?v=1', normalScale: 0.8, albedoMapUrl: '/assets/models/darwin4-albedo-enh.webp?v=1' },
    targetTriangles: 60000,
    prompt: 'Darwin candidate 4, Mixamo-rigged textured FBX, game-decimated.',
  },
  darwin5: {
    enabled: true,
    preload: false,
    path: '/assets/models/darwin5.glb',
    cacheKey: 'darwin5-height-aware-gather-push-20260623',
    // Darwin 5 test pass: native Mixamo clips plus carry/rifle/climb sets.
    // The runtime idle is the skinless 41-bone Mixamo clip from
    // assets-src/darwin/animations/states/darwin5-idle-new.fbx, transplanted
    // by matching identical Darwin5 bone names. Darwin5 crouch/traversal,
    // water-entry/exit, right-hand held-tool, small-wall climb, fieldwork, rest, fall, get-up, vault, strafe,
    // trip, jump-down, and running turn clips are likewise native 41-bone skinless clips.
    scale: 1.0,
    rotation: [0, 0, 0],
    yOffset: -0.025,
    visualGrounding: true,
    normalizeMaterials: true,
    materialLift: 0.045,
    materialEmissive: '#20170f',
    // Keep emissive very low; high self-light flattens the face/coat and fights
    // the outdoor light rig.
    materialEmissiveIntensity: 0.055,
    // A small envMap sheen keeps leather/cloth from reading as flat "velvet"
    // without creating an artificial player-only glow.
    materialUpgrade: { rimColor: '#ffdca8', rimPower: 5.0, rimIntensity: 0.055, roughness: 0.76, envMapIntensity: 0.12, toneMapped: true },
    targetTriangles: 60000,
    prompt: 'Darwin candidate 5, Mixamo-rigged test model with supplied idle, walking, and running animation clips.',
  },
  syms: {
    enabled: true,
    preload: false,
    path: '/assets/models/syms-animated.glb',
    scale: 0.98,
    rotation: [0, 0, 0],
    yOffset: 0,
    normalizeMaterials: true,
    materialLift: 0.1,
    materialEmissive: '#191b14',
    materialEmissiveIntensity: 0.18,
    targetTriangles: 10000,
    prompt: 'Stylized low-poly Syms Covington, young 1830s ship assistant and naturalist helper, practical sailor clothing, small specimen bag, historically grounded, readable silhouette, hand-painted texture, cel-shaded game asset, neutral pose, clean topology, GLB.',
  },
  crab: {
    enabled: true,
    path: '/assets/models/crab.glb',
    scale: 0.034,
    rotation: [-Math.PI / 2, 0, 0],
    yOffset: 0.05,
    normalizeMaterials: true,
    materialLift: 0.02,
    materialEmissive: '#3b1209',
    materialEmissiveIntensity: 0.1,
    targetTriangles: 3000,
    prompt: 'Stylized low-poly Galapagos Sally Lightfoot crab, red orange shell, readable claws and legs, hand-painted texture, cel-shaded game asset, clean topology, small web GLB, neutral pose.',
  },
  marineIguana: {
    enabled: true,
    path: '/assets/models/animals/runtime/marine-iguana.glb',
    scale: 0.074,
    rotation: [0, Math.PI, 0],
    yOffset: 0.08,
    normalizeMaterials: true,
    materialLift: 0.04,
    materialEmissive: '#0f120e',
    materialEmissiveIntensity: 0.08,
    targetTriangles: 5000,
    prompt: 'Stylized low-poly Galapagos marine iguana, black volcanic scales, blunt snout, dorsal spines, basking pose, readable silhouette, hand-painted texture, cel-shaded game asset, clean topology, GLB.',
  },
  lavalizard: {
    enabled: true,
    path: '/assets/models/animals/runtime/floreana-lava-lizard.glb',
    cacheKey: 'floreana-lava-lizard-double-side-20260623',
    scale: 0.88,
    rotation: [0, Math.PI, 0],
    yOffset: 0.02,
    normalizeMaterials: true,
    doubleSide: true,
    materialLift: 0.03,
    materialEmissive: '#14130f',
    materialEmissiveIntensity: 0.07,
    targetTriangles: 10000,
    prompt: 'Stylized low-poly Floreana lava lizard (Microlophus grayii), compact form, quick patrol motion, basking behavior, readable on volcanic rock, hand-painted texture, cel-shaded game asset, clean topology, GLB.',
  },
  mediumGroundFinch: {
    enabled: true,
    path: '/assets/models/animals/runtime/purple-finch.glb',
    scale: 0.42,
    rotation: [0, Math.PI, 0],
    yOffset: 0.08,
    normalizeMaterials: true,
    materialLift: 0.08,
    materialEmissive: '#1c130d',
    materialEmissiveIntensity: 0.08,
    targetTriangles: 2500,
    prompt: 'Stylized low-poly Galapagos medium ground finch, stout beak, brown plumage, readable silhouette, hand-painted texture, cel-shaded game asset, clean topology, GLB.',
  },
  floreanaGiantTortoise: {
    enabled: true,
    path: '/assets/models/animals/runtime/galapagos-giant-tortoise.glb',
    scale: 1.05,
    rotation: [0, Math.PI / 2, 0],
    yOffset: 0.03,
    normalizeMaterials: true,
    materialLift: 0.2,
    materialEmissive: '#17170f',
    materialEmissiveIntensity: 0.1,
    targetTriangles: 50000,
    prompt: 'Game-ready Floreana Galapagos giant tortoise, saddleback shell, heavy legs, dry scrub habitat, naturalistic muted shell color, optimized GLB.',
  },
  galapagosPenguin: {
    enabled: true,
    path: '/assets/models/animals/runtime/galapagos-penguin.glb',
    scale: 0.95,
    rotation: [0, Math.PI, 0],
    yOffset: 0.02,
    normalizeMaterials: true,
    materialLift: 0.04,
    materialEmissive: '#101820',
    materialEmissiveIntensity: 0.08,
    targetTriangles: 15000,
    prompt: 'Game-ready Galapagos penguin, small black and white penguin near lava rocks, naturalistic proportions, optimized GLB.',
  },
  flightlessCormorant: {
    enabled: true,
    preload: false,
    path: '/assets/models/animals/runtime/flightless-cormorant.glb',
    scale: 1.25,
    rotation: [0, Math.PI, 0],
    yOffset: 0.02,
    normalizeMaterials: true,
    materialLift: 0.05,
    materialEmissive: '#101513',
    materialEmissiveIntensity: 0.08,
    targetTriangles: 6500,
    prompt: 'Game-ready Galapagos flightless cormorant, compact dark coastal bird, small wings, sturdy legs, procedural walk animation clip, optimized GLB.',
  },
  frigatebird: {
    enabled: true,
    preload: false,
    path: '/assets/models/animals/runtime/magnificent-frigatebird.glb',
    cacheKey: 'frigatebird-rest-pose-run-20260623',
    scale: 1.35,
    rotation: [0, Math.PI, 0],
    yOffset: 0.03,
    normalizeMaterials: true,
    materialLift: 0.04,
    materialEmissive: '#0d1112',
    materialEmissiveIntensity: 0.08,
    targetTriangles: 5000,
    prompt: 'Game-ready Magnificent Frigatebird, black Galapagos seabird with forked tail and red gular pouch, simple procedural walk and run clips, optimized GLB.',
  },
  blueFootedBooby: {
    enabled: true,
    preload: false,
    path: '/assets/models/animals/runtime/blue-footed-booby.glb',
    cacheKey: 'blue-footed-booby-double-side-20260623',
    scale: 1.18,
    rotation: [0, Math.PI, 0],
    yOffset: 0.03,
    normalizeMaterials: true,
    doubleSide: true,
    materialLift: 0.035,
    materialEmissive: '#141413',
    materialEmissiveIntensity: 0.07,
    targetTriangles: 5000,
    prompt: 'Game-ready Blue-footed Booby, brown and white Galapagos seabird with blue feet, idle walk and run clips with wing flapping, optimized GLB.',
  },
  galapagosDoveRigged: {
    enabled: false,
    preload: false,
    path: '/assets/models/animals/runtime/dove-bird-rigged.glb',
    scale: 1,
    rotation: [0, 0, 0],
    yOffset: 0.03,
    normalizeMaterials: true,
    materialLift: 0.035,
    materialEmissive: '#14110d',
    materialEmissiveIntensity: 0.06,
    targetTriangles: 5000,
    prompt: 'Rigged low-poly Galapagos dove / shore bird candidate, imported for later Floreana dry-zone bird integration.',
  },
  greenTurtle: {
    enabled: true,
    preload: false,
    path: '/assets/models/animals/runtime/hawksbill-sea-turtle.glb',
    scale: 3.0,
    rotation: [0, 0, 0],
    yOffset: 0.12,
    normalizeMaterials: true,
    materialLift: 0.04,
    materialEmissive: '#0e1410',
    materialEmissiveIntensity: 0.06,
    targetTriangles: 8000,
    prompt: 'Rigged hawksbill sea turtle runtime replacement for the existing green-turtle slot, looping swim cycle, naturalistic mottled carapace, optimized GLB.',
  },
  animatedLowPolyFish: {
    enabled: true,
    preload: false,
    path: '/assets/models/animals/runtime/animated-low-poly-fish.glb',
    scale: 0.36,
    rotation: [0, 0, 0],
    yOffset: 0,
    normalizeMaterials: true,
    materialLift: 0.03,
    materialEmissive: '#0b1316',
    materialEmissiveIntensity: 0.04,
    targetTriangles: 1000,
    prompt: 'Small animated low-poly reef fish for instanced shallow-water schools at Northwest Reef.',
  },
  seaLion: {
    enabled: true,
    preload: false,
    path: '/assets/models/animals/runtime/sea-lion.glb',
    scale: 0.26,
    rotation: [0, 0, 0],
    yOffset: 0.19,
    normalizeMaterials: true,
    materialLift: 0.05,
    materialEmissive: '#14110d',
    materialEmissiveIntensity: 0.08,
    targetTriangles: 12500,
    prompt: 'Game-ready Galapagos sea lion (animated seal source mesh), morph-target idle animation, sleek wet coat, optimized GLB.',
  },
  cactus: {
    enabled: false,
    path: '/assets/models/cactus.glb',
    scale: 1,
    rotation: [0, 0, 0],
    yOffset: 0,
    targetTriangles: 1500,
    prompt: 'Stylized low-poly Galapagos Opuntia cactus tree, paddle pads, sparse spines, dry coastal scrub habitat, hand-painted texture, cel-shaded game prop, clean topology, GLB.',
  },
  galapagoscotton: {
    enabled: true,
    path: '/assets/models/nature/runtime-galapagos-cotton.glb',
    scale: 4.2,
    rotation: [0, 0, 0],
    yOffset: 0.02,
    normalizeMaterials: true,
    materialLift: 0.06,
    materialEmissive: '#171a0f',
    materialEmissiveIntensity: 0.06,
    targetTriangles: 5000,
    prompt: 'Stylized low-poly Galapagos cotton shrub, Gossypium darwinii, dry coastal scrub plant, broad green leaves, pale flowers or cotton bolls, hand-painted texture, cel-shaded game asset, optimized GLB.',
  },
  scalesiaPedunculataTree: {
    enabled: true,
    preload: false,
    path: '/assets/models/nature/runtime-scalesia-pedunculata-tree.glb',
    scale: 1,
    rotation: [0, 0, 0],
    yOffset: 0,
    normalizeMaterials: true,
    materialLift: 0.03,
    materialEmissive: '#162412',
    materialEmissiveIntensity: 0.06,
    targetTriangles: 8000,
    prompt: 'Stylized Galapagos Scalesia pedunculata tree, broad clustered leaves and humid highland canopy form, used sparsely in Floreana highland forest.',
  },
  mangroveTree: {
    enabled: true,
    preload: false,
    path: '/assets/models/nature/runtime-mangrove-tree.glb',
    scale: 1,
    rotation: [0, 0, 0],
    yOffset: 0,
    normalizeMaterials: true,
    materialLift: 0.03,
    materialEmissive: '#102113',
    materialEmissiveIntensity: 0.04,
    targetTriangles: 19037,
    prompt: 'Optimized textured mangrove tree with visible trunk and prop-root structure for brackish Floreana lagoon and mangrove-forest scenes.',
  },
  candelabraCactus: {
    enabled: true,
    preload: false,
    path: '/assets/models/nature/runtime-candelabra-cactus.glb',
    scale: 1,
    rotation: [0, 0, 0],
    yOffset: 0,
    normalizeMaterials: true,
    materialLift: 0.04,
    materialEmissive: '#17200d',
    materialEmissiveIntensity: 0.04,
    targetTriangles: 11321,
    prompt: 'Optimized Galapagos candelabra cactus, Jasminocereus style dry-zone columnar cactus for sparse arid coastal Floreana scrub.',
  },
  barnacle: {
    enabled: true,
    preload: false,
    path: '/assets/models/nature/runtime-barnacle-cluster.glb',
    scale: 0.42,
    rotation: [0, 0, 0],
    yOffset: 0.01,
    normalizeMaterials: true,
    materialLift: 0.08,
    materialEmissive: '#201811',
    materialEmissiveIntensity: 0.05,
    targetTriangles: 5000,
    prompt: 'Game-ready Galapagos volcanic shore barnacle cluster attached to intertidal basalt, compact pale shell plates, optimized GLB specimen prop.',
  },
  postOfficeBayBarrel: {
    enabled: true,
    preload: false,
    path: '/assets/models/nature/runtime-post-office-bay-barrel.glb',
    scale: 1,
    rotation: [0, 0, 0],
    yOffset: 0,
    normalizeMaterials: true,
    materialLift: 0.04,
    materialEmissive: '#1b1209',
    materialEmissiveIntensity: 0.05,
    targetTriangles: 5000,
    prompt: 'Large weathered wooden Post Office Bay barrel prop, salt-worn staves and iron bands, used as a breakable physics landmark near Darwin spawn.',
  },
  terracottaPot: {
    enabled: true,
    preload: false,
    path: '/assets/models/props/runtime-terracotta-pot.glb',
    scale: 1,
    rotation: [0, 0, 0],
    yOffset: 0,
    normalizeMaterials: true,
    materialLift: 0.05,
    materialEmissive: '#241009',
    materialEmissiveIntensity: 0.04,
    targetTriangles: 2494,
    prompt: 'Small weathered terracotta field pot prop for settlements and shore camps, pickupable and gently pushable.',
  },
  brokenWoodenCrate: {
    enabled: true,
    preload: false,
    path: '/assets/models/props/runtime-broken-wooden-crate.glb',
    scale: 1,
    rotation: [0, 0, 0],
    yOffset: 0,
    normalizeMaterials: true,
    materialLift: 0.04,
    materialEmissive: '#1b1008',
    materialEmissiveIntensity: 0.04,
    targetTriangles: 8432,
    prompt: 'Broken weathered wooden crate prop for Post Office Bay shore camp, heavy enough to push but not carry.',
  },
  shoreTurretShell: {
    enabled: true,
    preload: false,
    path: '/assets/models/shore/finds/turret-shell.glb',
    scale: 1,
    rotation: [0, 0, 0],
    yOffset: 0,
    normalizeMaterials: true,
    materialLift: 0.025,
    materialEmissive: '#20170f',
    materialEmissiveIntensity: 0.03,
    targetTriangles: 4000,
    prompt: 'Small turret shell collectible shore find for Galapagos beach biomes; spawned sparsely on sand strandlines.',
  },
  shoreJunoniaShell: {
    enabled: true,
    preload: false,
    path: '/assets/models/shore/finds/junonia-shell.glb',
    scale: 1,
    rotation: [Math.PI / 2, 0, 0],
    yOffset: 0,
    normalizeMaterials: true,
    materialLift: 0.025,
    materialEmissive: '#20170f',
    materialEmissiveIntensity: 0.03,
    targetTriangles: 5000,
    prompt: 'Junonia-style spotted shell collectible shore find; uncommon beach-object variant for Darwin to inspect or collect.',
  },
  shoreStarfish: {
    enabled: true,
    preload: false,
    path: '/assets/models/shore/finds/starfish.glb',
    scale: 1,
    rotation: [0, 0, 0],
    yOffset: 0,
    normalizeMaterials: true,
    materialLift: 0.025,
    materialEmissive: '#201008',
    materialEmissiveIntensity: 0.03,
    targetTriangles: 4000,
    prompt: 'Detailed starfish collectible shore find, placed rarely on wet and dry beach biomes.',
  },
  shoreLowPolyStarfish: {
    enabled: true,
    preload: false,
    path: '/assets/models/shore/finds/low-poly-starfish.glb',
    scale: 1,
    rotation: [-Math.PI / 2, 0, 0],
    yOffset: 0,
    normalizeMaterials: true,
    materialLift: 0.025,
    materialEmissive: '#201008',
    materialEmissiveIntensity: 0.03,
    targetTriangles: 1000,
    prompt: 'Small low-poly starfish collectible shore find, cheap enough for sparse repeated placement on beaches.',
  },
  basalt: {
    enabled: false,
    path: '/assets/models/basalt.glb',
    scale: 1,
    rotation: [0, 0, 0],
    yOffset: 0,
    targetTriangles: 1000,
    prompt: 'Stylized low-poly basalt lava rock sample, dark volcanic surface, angular fracture planes, hand-painted texture, cel-shaded game prop, clean topology, GLB.',
  },
  dryGrassPatch: {
    enabled: true,
    path: '/assets/models/nature/runtime-animated-dry-grass.glb',
    scale: 0.24,
    rotation: [0, 0, 0],
    yOffset: 0.02,
    normalizeMaterials: true,
    materialLift: 0.04,
    materialEmissive: '#1d1a0e',
    materialEmissiveIntensity: 0.08,
    targetTriangles: 3138,
    prompt: 'Optimized dry coastal Galapagos grass clump derived from animated_grass_-_vegetation.glb, stripped of texture and morph animation payloads, straw olive material, instanced arid-zone tufts for Floreana Post Office Bay.',
  },
  beagle: {
    enabled: true,
    preload: false,
    path: '/assets/models/ships/beagle-styrbjorn.glb',
    scale: 0.92,
    rotation: [0, 0, 0],
    yOffset: 0,
    targetTriangles: 45000,
    prompt: 'Stylized low-poly HMS Beagle survey brig, 1830s Royal Navy ship, masts and cream sails, dark hull, readable silhouette from shore, hand-painted texture, cel-shaded scenic game asset, clean topology, GLB.',
  },
};

export function getModelAsset(id) {
  return modelAssets[id] || null;
}
