// @ts-check

/**
 * Configuration shared by player, fauna, prop, and structure model loaders.
 * Less-common loader options remain available through the indexed portion while
 * the fields agents edit most often are checked explicitly.
 *
 * @typedef {Record<string, unknown> & {
 *   enabled: boolean,
 *   path: string,
 *   preload?: boolean,
 *   scale?: number | number[],
 *   rotation?: number[],
 *   yOffset?: number,
 *   cacheKey?: string,
 *   animationBanks?: Array<{id: string, path: string, cacheKey?: string, phase?: number}>,
 *   normalizeMaterials?: boolean,
 *   targetTriangles?: number,
 *   prompt?: string,
 * }} ModelAssetConfig
 */

export const DEFAULT_PLAYER_MODEL_ASSET_ID = 'darwin5';

/** @type {Record<string, ModelAssetConfig>} */
export const modelAssets = {
  darwin: {
    enabled: true,
    preload: false,
    path: '/assets/models/darwin-final-animated.glb',
    // Legacy primary Darwin kept for hotkey-9 A/B testing. Runtime traversal
    // clips are consolidated into this smaller GLB for quick fallback loading.
    // Keep candidate2 below for hotkey-9 visual A/B testing.
    scale: 1.56,
    rotation: [0, 0, 0],
    yOffset: 0,
    visualGrounding: true,
    normalizeMaterials: true,
    materialLift: 0.1,
    materialEmissive: '#20170f',
    materialEmissiveIntensity: 0.16,
    // Player-only material polish layered on top of the cel pipeline: a subtle
    // fresnel rim for silhouette readability plus world tone mapping so Darwin
    // sits in the scene instead of reading as separately lit.
    // Tunables — ask for a screenshot to dial in. Remove to revert.
    materialUpgrade: { rimColor: '#ffdca8', rimPower: 4.2, rimIntensity: 0.11, roughness: 0.74, toneMapped: true },
    targetTriangles: 12000,
    prompt: 'Stylized low-poly young Charles Darwin naturalist, 1835 Galapagos expedition, wide-brim straw hat, brown frock coat, waistcoat, specimen satchel, field notebook, historically grounded, readable silhouette, hand-painted texture, cel-shaded game asset, neutral A-pose, clean topology, GLB.',
  },
  darwinCandidate2: {
    enabled: true,
    preload: false,
    path: '/assets/models/darwin-candidate-2-animated.glb',
    scale: 1,
    rotation: [0, 0, 0],
    yOffset: 0,
    visualGrounding: true,
    normalizeMaterials: true,
    materialLift: 0.08,
    materialEmissive: '#20170f',
    materialEmissiveIntensity: 0.14,
    // Same player rim/sheen as V1 so the hotkey-9 A/B isolates mesh+texture,
    // not a separate player-lighting treatment.
    materialUpgrade: { rimColor: '#ffdca8', rimPower: 4.2, rimIntensity: 0.11, roughness: 0.74, toneMapped: true },
    targetTriangles: 50000,
    prompt: 'Mixamo-rigged Young Darwin candidate 2 with expanded locomotion, traversal, injured, water, and naturalist action animation set.',
  },
  darwinTripo: {
    enabled: true,
    preload: false,
    // ?v bust: the GLB was rebuilt in place (UV fix); bump this if you rebuild
    // it again so the browser refetches instead of serving a stale cached copy.
    path: '/assets/models/darwin-tripo.glb',
    // Tripo v3.1 mesh, Mixamo-rigged (mixamorig:), decimated 1.96M -> 60k,
    // re-textured + regraded (scripts/regrade-tripo-texture.mjs) + WebP,
    // normalized to 1.75m. No baked clips — borrows V2's full set via
    // animationSource (identical skeleton; both ~1.75m so no track rescale).
    animationSource: 'darwinCandidate2',
    scale: 1.0,
    rotation: [0, 0, 0],
    yOffset: 0,
    visualGrounding: true,
    normalizeMaterials: true,
    // Tripo albedo is already warm/graded; no cream lift, softer emissive, and
    // a higher roughness + gentler rim so the (lighter) skin doesn't blow out.
    materialLift: 0,
    materialEmissive: '#20170f',
    materialEmissiveIntensity: 0.09,
    materialUpgrade: { rimColor: '#ffdca8', rimPower: 4.3, rimIntensity: 0.1, roughness: 0.88, toneMapped: true },
    targetTriangles: 60000,
    prompt: 'Tripo v3.1 Young Darwin, segmented + Mixamo-rigged, game-decimated.',
  },
  darwin4: {
    enabled: true,
    preload: false,
    path: '/assets/models/darwin4.glb',
    // Darwin 4: Mixamo-rigged FBX with embedded texture, rebuilt with native
    // baked clips retargeted onto its own 41-bone armature. Do not borrow V2
    // clips at runtime; that rig mismatch distorts proportions during gait.
    // Source mesh is ~2.26m tall; 0.83 brings it in line with Syms and the
    // primary Darwin runtime height (~1.87m).
    scale: 0.83,
    rotation: [0, 0, 0],
    yOffset: 0,
    visualGrounding: true,
    normalizeMaterials: true,
    materialLift: 0.025,
    materialEmissive: '#20170f',
    // Match darwin5: drop the self-lit emissive glow at night, lower roughness +
    // add envMap sheen so cloth/leather read as material, not flat "velvet".
    materialEmissiveIntensity: 0.035,
    // toneMapped:true — test running the player through ACES like the world. Flip
    // to false (or remove) to revert to the cel-pipeline un-tonemapped look.
    // Sidecar maps (scripts/build-darwin-roughness.mjs + build-darwin-detail.mjs):
    //  roughnessMapUrl — leather glossier + waistcoat semi-gloss, cloth/skin at 0.6.
    //  normalMapUrl    — gentle derived micro-detail relief (normalScale tunes it).
    //  albedoMapUrl    — crisper albedo + tamed hot cream trousers.
    // ?v bump busts the browser cache when a map is regenerated.
    materialUpgrade: { rimColor: '#ffdca8', rimPower: 4.4, rimIntensity: 0.12, roughness: 0.64, envMapIntensity: 0.24, toneMapped: true, roughnessMapUrl: '/assets/models/darwin4-roughness.webp?v=1', normalMapUrl: '/assets/models/darwin4-normal.webp?v=1', normalScale: 0.8, albedoMapUrl: '/assets/models/darwin4-albedo-enh.webp?v=1' },
    targetTriangles: 60000,
    prompt: 'Darwin candidate 4, Mixamo-rigged textured FBX, game-decimated.',
  },
  darwin5: {
    enabled: true,
    preload: true,
    path: '/assets/models/darwin5.glb',
    cacheKey: 'darwin5-runtime-split-20260715a',
    // The boot GLB contains the skinned model plus dependable idle/locomotion
    // fallbacks. Deferred clips stream and parse in paced aerial-sequence
    // phases, then join the same mixer before the camera reaches the player.
    animationBanks: [
      {
        id: 'motion',
        path: '/assets/models/darwin5-motion-bank.glb',
        cacheKey: 'darwin5-runtime-split-20260715a',
        phase: 1,
      },
      {
        id: 'action',
        path: '/assets/models/darwin5-action-bank.glb',
        cacheKey: 'darwin5-runtime-split-20260715a',
        phase: 2,
      },
      {
        id: 'character',
        path: '/assets/models/darwin5-character-bank.glb',
        cacheKey: 'darwin5-runtime-split-20260715a',
        phase: 3,
      },
    ],
    // Darwin 5 is the current default player model: native Mixamo clips plus
    // carry/rifle/climb sets.
    // The runtime idle is the skinless 41-bone Mixamo clip from
    // assets-src/darwin/animations/states/darwin5-idle-new.fbx, transplanted
    // by matching identical Darwin5 bone names. Darwin5 crouch/traversal,
    // water-entry/exit, right-hand held-tool, small-wall climb, fieldwork, rest, fall, get-up, vault, strafe,
    // trip, jump-down, and running turn clips are likewise native 41-bone skinless clips.
    scale: 1.0,
    rotation: [0, 0, 0],
    yOffset: -0.025,
    receiveShadow: true,
    visualGrounding: true,
    normalizeMaterials: true,
    materialLift: 0.05,
    materialEmissive: '#20170f',
    // Keep emissive very low; high self-light flattens the face/coat and fights
    // the outdoor light rig.
    materialEmissiveIntensity: 0.035,
    // The envMap doubles as view-independent ambient (IBL diffuse + sheen):
    // the light rig deliberately starves fill on clear days, so this keeps the
    // back-lit player from crushing to black without a player-only glow.
    // Sidecar maps generated from the embedded Darwin5 atlas:
    // roughness adds material separation, normal adds cloth/leather relief, and
    // albedo keeps detail crisp without rebaking the GLB.
    materialUpgrade: { rimColor: '#ffdca8', rimPower: 5.0, rimIntensity: 0.045, roughness: 0.72, envMapIntensity: 0.3, toneMapped: true, roughnessMapUrl: '/assets/models/darwin5-roughness.webp?v=1', normalMapUrl: '/assets/models/darwin5-normal.webp?v=1', normalScale: 0.56, albedoMapUrl: '/assets/models/darwin5-albedo-enh.webp?v=1' },
    targetTriangles: 60000,
    prompt: 'Darwin candidate 5, Mixamo-rigged test model with supplied idle, walking, and running animation clips.',
  },
  // Separate in-game A/B candidate. Its Blender source and GLB are isolated
  // from the default Darwin5 asset, but it deliberately shares the verified
  // deferred animation banks and player behavior profile.
  darwin5BlinkPreview: {
    enabled: true,
    preload: false,
    path: '/assets/models/darwin5-blink-preview.glb',
    cacheKey: 'darwin5-blink-preview-20260717d',
    animationBanks: [
      {
        id: 'motion',
        path: '/assets/models/darwin5-motion-bank.glb',
        cacheKey: 'darwin5-runtime-split-20260715a',
        phase: 1,
      },
      {
        id: 'action',
        path: '/assets/models/darwin5-action-bank.glb',
        cacheKey: 'darwin5-runtime-split-20260715a',
        phase: 2,
      },
      {
        id: 'character',
        path: '/assets/models/darwin5-character-bank.glb',
        cacheKey: 'darwin5-runtime-split-20260715a',
        phase: 3,
      },
    ],
    animationProfile: 'darwin5',
    playerProfile: 'darwin5',
    scale: 1.0,
    rotation: [0, 0, 0],
    yOffset: -0.025,
    receiveShadow: true,
    visualGrounding: true,
    normalizeMaterials: true,
    materialLift: 0.05,
    materialEmissive: '#20170f',
    materialEmissiveIntensity: 0.035,
    materialUpgrade: { rimColor: '#ffdca8', rimPower: 5.0, rimIntensity: 0.045, roughness: 0.72, envMapIntensity: 0.3, toneMapped: true, roughnessMapUrl: '/assets/models/darwin5-roughness.webp?v=1', normalMapUrl: '/assets/models/darwin5-normal.webp?v=1', normalScale: 0.56, albedoMapUrl: '/assets/models/darwin5-albedo-enh.webp?v=1' },
    materialRegionUpgrade: {
      skin: {
        materialNames: ['Darwin5 skin', 'Darwin5 eyelid skin'],
        metalness: 0,
        useRoughnessMap: false,
        roughness: 0.62,
        normalScale: 0.2,
        specularIntensity: 0.32,
        clearcoat: 0.025,
        clearcoatRoughness: 0.5,
        envMapIntensity: 0.2,
      },
      hair: {
        materialNames: ['Darwin5 hair'],
        metalness: 0,
        useRoughnessMap: false,
        roughness: 0.84,
        normalScale: 0.3,
        colorBlend: '#c2cad2',
        colorBlendAmount: 0.14,
        colorScale: 0.86,
        specularIntensity: 0.2,
        envMapIntensity: 0.13,
      },
      brassButtons: {
        materialNames: ['Darwin5 brass buttons'],
        metalness: 1,
        useAlbedoMap: false,
        useRoughnessMap: false,
        roughness: 0.045,
        useNormalMap: false,
        colorBlend: '#f0b43d',
        colorBlendAmount: 0.18,
        envMapIntensity: 1.5,
        directSpecularGlint: {
          color: '#fff0b5',
          specularBoost: 6.5,
          bloomStrength: 1.35,
          threshold: 0.012,
          thresholdEnd: 0.14,
          focus: 1.9,
        },
      },
    },
    blinkMorph: {
      name: 'Blink',
      minInterval: 2.8,
      maxInterval: 6.4,
      closeDuration: 0.12,
      holdDuration: 0.07,
      openDuration: 0.21,
      durationVariation: 0.1,
      doubleBlinkChance: 0.12,
      doubleBlinkDelay: 0.19,
    },
    targetTriangles: 60500,
    prompt: 'Darwin5 in-game blink preview with Blender-authored eyelid morph surfaces; not the production default.',
  },
  syms: {
    enabled: true,
    preload: false,
    path: '/assets/models/syms-animated.glb',
    cacheKey: 'syms-2k-webp-20260715',
    scale: 0.98,
    rotation: [0, 0, 0],
    yOffset: 0,
    normalizeMaterials: true,
    materialLift: 0.1,
    materialEmissive: '#191b14',
    materialEmissiveIntensity: 0.18,
    // Matches the darwin5 fix: a faint envMap sheen keeps him from crushing to
    // black when backlit on a clear day, without a player-only glow.
    materialUpgrade: { rimIntensity: 0.02, rimPower: 5.0, envMapIntensity: 0.2 },
    targetTriangles: 10000,
    prompt: 'Stylized low-poly Syms Covington, young 1830s ship assistant and naturalist helper, practical sailor clothing, small specimen bag, historically grounded, readable silhouette, hand-painted texture, cel-shaded game asset, neutral pose, clean topology, GLB.',
  },
  crab: {
    enabled: true,
    path: '/assets/models/animals/runtime/bundle-sally-lightfoot-crab.glb',
    cacheKey: 'bundle-sally-lightfoot-crab-fbx-20260706',
    scale: 0.3,
    rotation: [0, 0, 0],
    yOffset: 0.035,
    normalizeMaterials: true,
    doubleSide: true,
    materialLift: 0.015,
    materialEmissive: '#3b1209',
    materialEmissiveIntensity: 0.08,
    materialUpgrade: { rimIntensity: 0.02, rimPower: 5.0, envMapIntensity: 0.2 },
    targetTriangles: 3000,
    prompt: 'Bundle animated crab retargeted as a Galapagos Sally Lightfoot crab runtime test, red orange shell, readable claws and legs, walk, strafe, eat, and reaction clips.',
  },
  settlementCat: {
    enabled: true,
    path: '/assets/models/animals/runtime/settlement-cat.glb',
    cacheKey: 'settlement-cat-fbx-20260706',
    scale: 1.3,
    rotation: [0, 0, 0],
    yOffset: 0.035,
    normalizeMaterials: true,
    doubleSide: true,
    materialLift: 0.015,
    materialEmissive: '#1c1712',
    materialEmissiveIntensity: 0.06,
    materialUpgrade: { rimIntensity: 0.015, rimPower: 5.0, envMapIntensity: 0.18 },
    targetTriangles: 3000,
    prompt: 'Single animated settlement cat for Asilo de la Paz / Penal Colony testing, low-poly fur texture, purr, clean, stretch, and walk clips.',
  },
  feralGoat: {
    enabled: true,
    preload: false,
    path: '/assets/models/animals/runtime/feral-goat.glb',
    cacheKey: 'feral-goat-fbx-runtime-webp-20260708',
    scale: 0.72,
    rotation: [0, 0, 0],
    yOffset: 0.025,
    normalizeMaterials: true,
    doubleSide: true,
    forceOpaque: true,
    castShadow: true,
    materialLift: 0.025,
    materialEmissive: '#1d1710',
    materialEmissiveIntensity: 0.045,
    materialUpgrade: { rimIntensity: 0.015, rimPower: 5.0, envMapIntensity: 0.16 },
    targetTriangles: 1500,
    prompt: 'Animated feral goat runtime asset for Floreana highland and settlement maps, 41-bone rig, walk, trot, run, browse/idle, sleep, laydown, wake, kick, and wound clips.',
  },
  feralHorse: {
    enabled: true,
    preload: false,
    path: '/assets/models/animals/runtime/feral-horse.glb',
    cacheKey: 'feral-horse-fbx-runtime-resampled-webp-20260708',
    scale: 1.0,
    rotation: [0, 0, 0],
    yOffset: 0.035,
    normalizeMaterials: true,
    doubleSide: true,
    forceOpaque: true,
    castShadow: true,
    materialLift: 0.02,
    materialEmissive: '#18120e',
    materialEmissiveIntensity: 0.035,
    materialUpgrade: { rimIntensity: 0.012, rimPower: 5.0, envMapIntensity: 0.15 },
    targetTriangles: 7200,
    prompt: 'Animated feral horse runtime asset for the penal colony settlement, resampled 81-bone rig with idle, restless, hoof scrape, walk, run, rearing, bucking, attack, jump, lying, get-up, and reaction clips.',
  },
  jackoMonkey: {
    enabled: true,
    preload: false,
    path: '/assets/models/animals/runtime/jacko-monkey.glb',
    cacheKey: 'jacko-monkey-fbx-runtime-20260706',
    // Native exported height is about 0.85m; keep Jacko smaller than Darwin
    // but large enough to read as a shipboard NPC from the Beagle camera.
    scale: 1.08,
    rotation: [0, 0, 0],
    yOffset: 0.025,
    normalizeMaterials: true,
    doubleSide: true,
    forceOpaque: true,
    castShadow: true,
    frustumCulled: false,
    materialLift: 0.035,
    materialEmissive: '#1a120d',
    materialEmissiveIntensity: 0.055,
    materialUpgrade: { rimIntensity: 0.02, rimPower: 5.0, envMapIntensity: 0.18 },
    targetTriangles: 3500,
    prompt: 'Rigged animated capuchin-like ship monkey mascot for HMS Beagle deck, small relative to Darwin, with idle, walk, run, and mischievous reaction clips.',
  },
  marineIguana: {
    enabled: true,
    path: '/assets/models/animals/runtime/marine-iguana.glb',
    scale: 0.04,
    rotation: [0, Math.PI, 0],
    yOffset: 0.08,
    normalizeMaterials: true,
    materialLift: 0.04,
    materialEmissive: '#0f120e',
    materialEmissiveIntensity: 0.08,
    materialUpgrade: { rimIntensity: 0.02, rimPower: 5.0, envMapIntensity: 0.2 },
    targetTriangles: 5000,
    prompt: 'Stylized low-poly Galapagos marine iguana, black volcanic scales, blunt snout, dorsal spines, basking pose, readable silhouette, hand-painted texture, cel-shaded game asset, clean topology, GLB.',
  },
  lavalizard: {
    enabled: true,
    path: '/assets/models/animals/runtime/floreana-lava-lizard.glb',
    cacheKey: 'floreana-lava-lizard-double-side-20260623',
    scale: 0.55,
    rotation: [0, Math.PI, 0],
    yOffset: 0.02,
    normalizeMaterials: true,
    doubleSide: true,
    materialLift: 0.03,
    materialEmissive: '#14130f',
    materialEmissiveIntensity: 0.07,
    materialUpgrade: { rimIntensity: 0.02, rimPower: 5.0, envMapIntensity: 0.2 },
    targetTriangles: 10000,
    prompt: 'Stylized low-poly Floreana lava lizard (Microlophus grayii), compact form, quick patrol motion, basking behavior, readable on volcanic rock, hand-painted texture, cel-shaded game asset, clean topology, GLB.',
  },
  mediumGroundFinch: {
    enabled: true,
    path: '/assets/models/animals/runtime/purple-finch.glb',
    // Imported bounds are only about 0.11m beak-to-tail. Use a readable
    // field-specimen scale so it registers as a small bird beside Darwin
    // instead of disappearing into the terrain grain.
    scale: 4.0,
    rotation: [0, Math.PI, 0],
    yOffset: 0.04,
    normalizeMaterials: true,
    materialLift: 0.08,
    materialEmissive: '#1c130d',
    materialEmissiveIntensity: 0.08,
    materialUpgrade: { rimIntensity: 0.02, rimPower: 5.0, envMapIntensity: 0.2 },
    targetTriangles: 2500,
    prompt: 'Stylized low-poly Galapagos medium ground finch, stout beak, brown plumage, readable silhouette, hand-painted texture, cel-shaded game asset, clean topology, GLB.',
  },
  floreanaGiantTortoise: {
    enabled: true,
    path: '/assets/models/animals/runtime/galapagos-giant-tortoise.glb',
    scale: 1.05,
    rotation: [0, Math.PI / 2, 0],
    yOffset: 0.03,
    normalizeMaterials: true,
    materialLift: 0.2,
    materialEmissive: '#17170f',
    materialEmissiveIntensity: 0.1,
    materialUpgrade: { rimIntensity: 0.02, rimPower: 5.0, envMapIntensity: 0.2 },
    targetTriangles: 50000,
    prompt: 'Game-ready Floreana Galapagos giant tortoise, saddleback shell, heavy legs, dry scrub habitat, naturalistic muted shell color, optimized GLB.',
  },
  playableTortoiseV2: {
    enabled: true,
    path: '/assets/models/animals/runtime/playable-tortoise-v2.glb',
    scale: 1.05,
    rotation: [Math.PI / 2, 0, 0],
    yOffset: 0.24,
    normalizeMaterials: false,
    materialUpgrade: { rimIntensity: 0.015, rimPower: 5.0, envMapIntensity: 0.18 },
    targetTriangles: 35000,
    prompt: 'Playable Galapagos giant tortoise v2, custom Blender hierarchy rig, high domed saddleback shell, wrinkled neck, smaller head, columnar legs, broad toe-knuckled feet, packed procedural shell and skin textures, idle/walk/eat/sleep/defecate clips.',
  },
  tripoTortoiseRigged: {
    enabled: true,
    path: '/assets/models/animals/runtime/tripo-tortoise-rigged.glb',
    cacheKey: 'tripo-rig-heightened-core-20260706',
    scale: 2.15,
    rotation: [0, Math.PI, 0],
    yOffset: 0.075,
    visualGrounding: true,
    normalizeMaterials: false,
    materialUpgrade: { rimIntensity: 0.01, rimPower: 5.0, envMapIntensity: 0.22 },
    targetTriangles: 5000,
    prompt: 'Playable Galapagos tortoise rebuilt from Tripo visual mesh and PBR textures with a clean custom armature, four independent leg chains, neck/head/jaw/tail controls, and idle/walk/eat/sleep/defecate clips.',
  },
  galapagosPenguin: {
    enabled: true,
    path: '/assets/models/animals/runtime/galapagos-penguin.glb',
    scale: 0.62,
    rotation: [0, Math.PI, 0],
    yOffset: 0.02,
    normalizeMaterials: true,
    materialLift: 0.04,
    materialEmissive: '#101820',
    materialEmissiveIntensity: 0.08,
    materialUpgrade: { rimIntensity: 0.02, rimPower: 5.0, envMapIntensity: 0.2 },
    targetTriangles: 15000,
    prompt: 'Game-ready Galapagos penguin, small black and white penguin near lava rocks, naturalistic proportions, optimized GLB.',
  },
  flightlessCormorant: {
    enabled: true,
    preload: false,
    path: '/assets/models/animals/runtime/flightless-cormorant.glb',
    scale: 1.25,
    rotation: [0, Math.PI, 0],
    yOffset: 0.02,
    normalizeMaterials: true,
    materialLift: 0.05,
    materialEmissive: '#101513',
    materialEmissiveIntensity: 0.08,
    materialUpgrade: { rimIntensity: 0.02, rimPower: 5.0, envMapIntensity: 0.2 },
    targetTriangles: 6500,
    prompt: 'Game-ready Galapagos flightless cormorant, compact dark coastal bird, small wings, sturdy legs, procedural walk animation clip, optimized GLB.',
  },
  frigatebird: {
    enabled: true,
    preload: false,
    path: '/assets/models/animals/runtime/magnificent-frigatebird.glb',
    cacheKey: 'frigatebird-rest-pose-run-20260623',
    scale: 1.35,
    rotation: [0, Math.PI, 0],
    yOffset: 0.03,
    normalizeMaterials: true,
    materialLift: 0.04,
    materialEmissive: '#0d1112',
    materialEmissiveIntensity: 0.08,
    materialUpgrade: { rimIntensity: 0.02, rimPower: 5.0, envMapIntensity: 0.2 },
    targetTriangles: 5000,
    prompt: 'Game-ready Magnificent Frigatebird, black Galapagos seabird with forked tail and red gular pouch, simple procedural walk and run clips, optimized GLB.',
  },
  blueFootedBooby: {
    enabled: true,
    preload: false,
    path: '/assets/models/animals/runtime/blue-footed-booby.glb',
    cacheKey: 'blue-footed-booby-double-side-20260623',
    scale: 1.0,
    rotation: [0, Math.PI, 0],
    yOffset: 0.03,
    normalizeMaterials: true,
    doubleSide: true,
    materialLift: 0.035,
    materialEmissive: '#141413',
    materialEmissiveIntensity: 0.07,
    materialUpgrade: { rimIntensity: 0.02, rimPower: 5.0, envMapIntensity: 0.2 },
    targetTriangles: 5000,
    prompt: 'Game-ready Blue-footed Booby, brown and white Galapagos seabird with blue feet, idle walk and run clips with wing flapping, optimized GLB.',
  },
  galapagosDoveRigged: {
    enabled: false,
    preload: false,
    path: '/assets/models/animals/runtime/dove-bird-rigged.glb',
    scale: 1,
    rotation: [0, 0, 0],
    yOffset: 0.03,
    normalizeMaterials: true,
    materialLift: 0.035,
    materialEmissive: '#14110d',
    materialEmissiveIntensity: 0.06,
    materialUpgrade: { rimIntensity: 0.02, rimPower: 5.0, envMapIntensity: 0.2 },
    targetTriangles: 5000,
    prompt: 'Rigged low-poly Galapagos dove / shore bird candidate, imported for later Floreana dry-zone bird integration.',
  },
  greenTurtle: {
    enabled: true,
    preload: false,
    path: '/assets/models/animals/runtime/hawksbill-sea-turtle.glb',
    scale: 3.0,
    rotation: [0, 0, 0],
    yOffset: 0.12,
    normalizeMaterials: true,
    materialLift: 0.04,
    materialEmissive: '#0e1410',
    materialEmissiveIntensity: 0.06,
    materialUpgrade: { rimIntensity: 0.02, rimPower: 5.0, envMapIntensity: 0.2 },
    targetTriangles: 8000,
    prompt: 'Rigged hawksbill sea turtle runtime replacement for the existing green-turtle slot, looping swim cycle, naturalistic mottled carapace, optimized GLB.',
  },
  animatedLowPolyFish: {
    enabled: true,
    preload: false,
    path: '/assets/models/animals/runtime/animated-low-poly-fish.glb',
    scale: 0.36,
    rotation: [0, 0, 0],
    yOffset: 0,
    normalizeMaterials: true,
    materialLift: 0.03,
    materialEmissive: '#0b1316',
    materialEmissiveIntensity: 0.04,
    materialUpgrade: { rimIntensity: 0.02, rimPower: 5.0, envMapIntensity: 0.2 },
    targetTriangles: 1000,
    prompt: 'Small animated low-poly reef fish for instanced shallow-water schools at Northwest Reef.',
  },
  seaLion: {
    enabled: true,
    preload: false,
    path: '/assets/models/animals/runtime/sea-lion.glb',
    scale: 0.26,
    rotation: [0, 0, 0],
    yOffset: 0.19,
    normalizeMaterials: true,
    materialLift: 0.05,
    materialEmissive: '#14110d',
    materialEmissiveIntensity: 0.08,
    materialUpgrade: { rimIntensity: 0.02, rimPower: 5.0, envMapIntensity: 0.2 },
    targetTriangles: 12500,
    prompt: 'Game-ready Galapagos sea lion (animated seal source mesh), morph-target idle animation, sleek wet coat, optimized GLB.',
  },
  flamingoAnimated: {
    enabled: true,
    preload: false,
    path: '/assets/models/animals/runtime/flamingo-animated.glb',
    cacheKey: 'flamingo-fbx-runtime-20260703',
    scale: 2.35,
    rotation: [0, 0, 0],
    yOffset: 0.03,
    normalizeMaterials: true,
    doubleSide: true,
    materialLift: 0.025,
    materialEmissive: '#221113',
    materialEmissiveIntensity: 0.045,
    materialUpgrade: { rimIntensity: 0.02, rimPower: 5.0, envMapIntensity: 0.18 },
    targetTriangles: 2500,
    prompt: 'Animated American flamingo runtime candidate with walk, feeding/idle, one-leg, and sleep clips for Floreana lagoon specimens.',
  },
  flyingFlamingo: {
    enabled: true,
    preload: false,
    path: '/assets/models/animals/runtime/flying-flamingo.glb',
    cacheKey: 'flying-flamingo-runtime-scaled-20260704',
    scale: 0.011,
    rotation: [0, 0, 0],
    yOffset: 0,
    normalizeMaterials: true,
    doubleSide: true,
    materialLift: 0.025,
    materialEmissive: '#221113',
    materialEmissiveIntensity: 0.04,
    materialUpgrade: { rimIntensity: 0.02, rimPower: 5.0, envMapIntensity: 0.16 },
    targetTriangles: 1200,
    prompt: 'Small animated flying flamingo GLB for distant non-interactive lagoon flock loops.',
  },
  seagull: {
    enabled: true,
    preload: false,
    path: '/assets/models/animals/runtime/seagull.glb',
    cacheKey: 'seagull-fbx-runtime-facing-20260703',
    scale: 1.15,
    rotation: [0, Math.PI, 0],
    yOffset: 0.02,
    normalizeMaterials: true,
    doubleSide: true,
    materialLift: 0.02,
    materialEmissive: '#141414',
    materialEmissiveIntensity: 0.045,
    materialUpgrade: { rimIntensity: 0.02, rimPower: 5.0, envMapIntensity: 0.2 },
    targetTriangles: 2500,
    prompt: 'Animated gull/seagull runtime candidate with walk, run, fly, glide, eat, look, and preen/clearing clips for coastal bird testing.',
  },
  hermitCrab: {
    enabled: true,
    preload: false,
    path: '/assets/models/animals/runtime/hermit-crab.glb',
    cacheKey: 'hermit-crab-fbx-runtime-20260703',
    scale: 0.42,
    rotation: [0, 0, 0],
    yOffset: 0.02,
    normalizeMaterials: true,
    materialLift: 0.03,
    materialEmissive: '#1d110b',
    materialEmissiveIntensity: 0.06,
    materialUpgrade: { rimIntensity: 0.02, rimPower: 5.0, envMapIntensity: 0.18 },
    targetTriangles: 4000,
    prompt: 'Animated hermit crab runtime candidate with walk, slow walk, burrow, emerge, eat, sleep, fighting, pinchers, knockback, and death clips for beach/intertidal testing.',
  },
  cactus: {
    enabled: false,
    path: '/assets/models/cactus.glb',
    scale: 1,
    rotation: [0, 0, 0],
    yOffset: 0,
    targetTriangles: 1500,
    prompt: 'Stylized low-poly Galapagos Opuntia cactus tree, paddle pads, sparse spines, dry coastal scrub habitat, hand-painted texture, cel-shaded game prop, clean topology, GLB.',
  },
  galapagoscotton: {
    enabled: true,
    path: '/assets/models/nature/runtime-galapagos-cotton.glb',
    scale: 4.2,
    rotation: [0, 0, 0],
    yOffset: 0.02,
    normalizeMaterials: true,
    materialLift: 0.06,
    materialEmissive: '#171a0f',
    materialEmissiveIntensity: 0.06,
    targetTriangles: 5000,
    prompt: 'Stylized low-poly Galapagos cotton shrub, Gossypium darwinii, dry coastal scrub plant, broad green leaves, pale flowers or cotton bolls, hand-painted texture, cel-shaded game asset, optimized GLB.',
  },
  darwiniothamnusShrub: {
    enabled: true,
    preload: false,
    path: '/assets/models/nature/runtime-darwiniothamnus.glb',
    cacheKey: 'darwiniothamnus-tenuifolius-nine-variants-20260716',
    scale: 1,
    rotation: [0, 0, 0],
    yOffset: 0,
    normalizeMaterials: true,
    materialLift: 0.04,
    materialEmissive: '#17200f',
    materialEmissiveIntensity: 0.045,
    targetTriangles: 18000,
    prompt: "Nine centered upright shrub forms adapted at runtime as Floreana's Darwiniothamnus tenuifolius; ecology layers choose one mesh variant per instanced scatter item.",
  },
  scalesiaPedunculataTree: {
    enabled: true,
    preload: false,
    path: '/assets/models/nature/runtime-scalesia-pedunculata-tree.glb',
    scale: 1,
    rotation: [0, 0, 0],
    yOffset: 0,
    normalizeMaterials: true,
    materialLift: 0.03,
    materialEmissive: '#162412',
    materialEmissiveIntensity: 0.06,
    targetTriangles: 8000,
    prompt: 'Stylized Galapagos Scalesia pedunculata tree, broad clustered leaves and humid highland canopy form, used sparsely in Floreana highland forest.',
  },
  mangroveTree: {
    enabled: true,
    preload: false,
    path: '/assets/models/nature/runtime-mangrove-tree.glb',
    scale: 1,
    rotation: [0, 0, 0],
    yOffset: 0,
    normalizeMaterials: true,
    materialLift: 0.03,
    materialEmissive: '#102113',
    materialEmissiveIntensity: 0.04,
    targetTriangles: 19037,
    prompt: 'Optimized textured mangrove tree with visible trunk and prop-root structure for brackish Floreana lagoon and mangrove-forest scenes.',
  },
  candelabraCactus: {
    enabled: true,
    preload: false,
    path: '/assets/models/nature/runtime-candelabra-cactus.glb',
    scale: 1,
    rotation: [0, 0, 0],
    yOffset: 0,
    normalizeMaterials: true,
    materialLift: 0.04,
    materialEmissive: '#17200d',
    materialEmissiveIntensity: 0.04,
    targetTriangles: 11321,
    prompt: 'Optimized Galapagos candelabra cactus, Jasminocereus style dry-zone columnar cactus for sparse arid coastal Floreana scrub.',
  },
  barnacle: {
    enabled: true,
    preload: false,
    path: '/assets/models/nature/runtime-barnacle-cluster.glb',
    scale: 0.2,
    rotation: [0, 0, 0],
    yOffset: 0.01,
    normalizeMaterials: true,
    materialLift: 0.08,
    materialEmissive: '#201811',
    materialEmissiveIntensity: 0.05,
    targetTriangles: 5000,
    prompt: 'Game-ready Galapagos volcanic shore barnacle cluster attached to intertidal basalt, compact pale shell plates, optimized GLB specimen prop.',
  },
  postOfficeBayBarrel: {
    enabled: true,
    preload: false,
    path: '/assets/models/nature/runtime-post-office-bay-barrel.glb',
    scale: 1,
    rotation: [0, 0, 0],
    yOffset: 0,
    normalizeMaterials: true,
    materialLift: 0.04,
    materialEmissive: '#1b1209',
    materialEmissiveIntensity: 0.05,
    targetTriangles: 5000,
    prompt: 'Large weathered wooden Post Office Bay barrel prop, salt-worn staves and iron bands, used as a breakable physics landmark near Darwin spawn.',
  },
  terracottaPot: {
    enabled: true,
    preload: false,
    path: '/assets/models/props/runtime-terracotta-pot.glb',
    scale: 1,
    rotation: [0, 0, 0],
    yOffset: 0,
    normalizeMaterials: true,
    materialLift: 0.05,
    materialEmissive: '#241009',
    materialEmissiveIntensity: 0.04,
    targetTriangles: 2494,
    prompt: 'Small weathered terracotta field pot prop for settlements and shore camps, pickupable and gently pushable.',
  },
  brokenWoodenCrate: {
    enabled: true,
    preload: false,
    path: '/assets/models/props/runtime-broken-wooden-crate.glb',
    scale: 1,
    rotation: [0, 0, 0],
    yOffset: 0,
    normalizeMaterials: true,
    materialLift: 0.04,
    materialEmissive: '#1b1008',
    materialEmissiveIntensity: 0.04,
    targetTriangles: 8432,
    prompt: 'Broken weathered wooden crate prop for Post Office Bay shore camp, heavy enough to push but not carry.',
  },
  shoreTurretShell: {
    enabled: true,
    preload: false,
    path: '/assets/models/shore/finds/turret-shell.glb',
    scale: 1,
    rotation: [0, 0, 0],
    yOffset: 0,
    normalizeMaterials: true,
    materialLift: 0.025,
    materialEmissive: '#20170f',
    materialEmissiveIntensity: 0.03,
    targetTriangles: 4000,
    prompt: 'Small turret shell collectible shore find for Galapagos beach biomes; spawned sparsely on sand strandlines.',
  },
  shoreJunoniaShell: {
    enabled: true,
    preload: false,
    path: '/assets/models/shore/finds/junonia-shell.glb',
    scale: 1,
    rotation: [Math.PI / 2, 0, 0],
    yOffset: 0,
    normalizeMaterials: true,
    materialLift: 0.025,
    materialEmissive: '#20170f',
    materialEmissiveIntensity: 0.03,
    targetTriangles: 5000,
    prompt: 'Junonia-style spotted shell collectible shore find; uncommon beach-object variant for Darwin to inspect or collect.',
  },
  shoreStarfish: {
    enabled: true,
    preload: false,
    path: '/assets/models/shore/finds/starfish.glb',
    scale: 1,
    rotation: [0, 0, 0],
    yOffset: 0,
    normalizeMaterials: true,
    materialLift: 0.025,
    materialEmissive: '#201008',
    materialEmissiveIntensity: 0.03,
    targetTriangles: 4000,
    prompt: 'Detailed starfish collectible shore find, placed rarely on wet and dry beach biomes.',
  },
  shoreLowPolyStarfish: {
    enabled: true,
    preload: false,
    path: '/assets/models/shore/finds/low-poly-starfish.glb',
    scale: 1,
    rotation: [-Math.PI / 2, 0, 0],
    yOffset: 0,
    normalizeMaterials: true,
    materialLift: 0.025,
    materialEmissive: '#201008',
    materialEmissiveIntensity: 0.03,
    targetTriangles: 1000,
    prompt: 'Small low-poly starfish collectible shore find, cheap enough for sparse repeated placement on beaches.',
  },
  basalt: {
    enabled: false,
    path: '/assets/models/basalt.glb',
    scale: 1,
    rotation: [0, 0, 0],
    yOffset: 0,
    targetTriangles: 1000,
    prompt: 'Stylized low-poly basalt lava rock sample, dark volcanic surface, angular fracture planes, hand-painted texture, cel-shaded game prop, clean topology, GLB.',
  },
  dryGrassPatch: {
    enabled: true,
    path: '/assets/models/nature/runtime-animated-dry-grass.glb',
    scale: 0.24,
    rotation: [0, 0, 0],
    yOffset: 0.02,
    normalizeMaterials: true,
    materialLift: 0.04,
    materialEmissive: '#1d1a0e',
    materialEmissiveIntensity: 0.08,
    targetTriangles: 3138,
    prompt: 'Optimized dry coastal Galapagos grass clump derived from animated_grass_-_vegetation.glb, stripped of texture and morph animation payloads, straw olive material, instanced arid-zone tufts for Floreana Post Office Bay.',
  },
  beagle: {
    enabled: true,
    preload: false,
    path: '/assets/models/ships/beagle-styrbjorn.glb',
    scale: 0.92,
    rotation: [0, 0, 0],
    yOffset: 0,
    targetTriangles: 45000,
    prompt: 'Stylized low-poly HMS Beagle survey brig, 1830s Royal Navy ship, masts and cream sails, dark hull, readable silhouette from shore, hand-painted texture, cel-shaded scenic game asset, clean topology, GLB.',
  },
  beagleDeckShip: {
    enabled: true,
    preload: false,
    path: '/assets/models/ships/hms-beagle-deck.glb',
    scale: 1.8,
    rotation: [0, 0, 0],
    yOffset: 0,
    targetTriangles: 90000,
    // Procedurally built (not generated): scripts/blender_build_hms_beagle_deck.py.
    // Walkable-scale 1835 bark-rigged Beagle for the BEAGLE deck region; hull
    // wraps the region's terrain plateau (see world/regions/beagleDeck/hull.js).
    prompt: 'Walkable HMS Beagle, 1835 bark rig at anchor: lofted hull with copper bottom and white gunport band, bulwarks, furled sails, quarter davit whaleboats, deck fittings at player scale.',
  },
  beagleCabinShip: {
    enabled: true,
    preload: false,
    path: '/assets/models/ships/hms-beagle-cabin.glb',
    scale: 1,
    rotation: [0, 0, 0],
    yOffset: 0,
    targetTriangles: 65000,
    // Procedurally built from the shared indoor blueprint by
    // scripts/blender_build_hms_beagle_cabin.py.
    prompt: 'Large playable aft interior of HMS Beagle: captain cabin, drawing cabin and library with curved hull walls, stern windows, beams, fitted furniture, berth, hammock and scientific instruments.',
  },
  beagleCabinChair: { enabled: true, preload: false, path: '/assets/models/props/beagle-cabin/cabin-chair.glb', scale: 1, rotation: [0, 0, 0], yOffset: 0, preserveMaterials: true, targetTriangles: 7000, prompt: 'Textured 1830s ship cabin ladder-back chair with turned legs and stretchers.' },
  beagleCabinStool: { enabled: true, preload: false, path: '/assets/models/props/beagle-cabin/folding-stool.glb', scale: 1, rotation: [0, 0, 0], yOffset: 0, preserveMaterials: true, targetTriangles: 5000, prompt: 'Folding campaign stool with crossed oak frames, brass pivots, and canvas seat.' },
  beagleCabinSeaChest: { enabled: true, preload: false, path: '/assets/models/props/beagle-cabin/sea-chest.glb', scale: 1, rotation: [0, 0, 0], yOffset: 0, preserveMaterials: true, targetTriangles: 8000, prompt: 'Varnished oak sea chest with iron strapping, side handles, and brass lock plate.' },
  beagleCabinBucket: { enabled: true, preload: false, path: '/assets/models/props/beagle-cabin/stave-bucket.glb', scale: 1, rotation: [0, 0, 0], yOffset: 0, preserveMaterials: true, targetTriangles: 5000, prompt: 'Tapered wooden stave bucket with blackened iron hoops and swinging handle.' },
  beagleCabinRolledChart: { enabled: true, preload: false, path: '/assets/models/props/beagle-cabin/rolled-chart.glb', scale: 1, rotation: [0, 0, 0], yOffset: 0, preserveMaterials: true, targetTriangles: 3000, prompt: 'Tightly rolled cream survey chart secured by two brown cords.' },
  beagleCabinChartWeight: { enabled: true, preload: false, path: '/assets/models/props/beagle-cabin/chart-weight.glb', scale: 1, rotation: [0, 0, 0], yOffset: 0, preserveMaterials: true, targetTriangles: 3000, prompt: 'Small turned polished-brass chart weight with ringed foot and spherical knob.' },
  beagleCabinTinMug: { enabled: true, preload: false, path: '/assets/models/props/beagle-cabin/tin-mug.glb', scale: 1, rotation: [0, 0, 0], yOffset: 0, preserveMaterials: true, targetTriangles: 3000, prompt: 'Open pewter shipboard mug with rolled lip and curved handle.' },
  // Shared, procedurally authored period lighting props. These are generated by
  // scripts/blender_build_period_lighting_props.py and deliberately reused
  // across the Beagle and Lawson house so brass/glass quality stays consistent.
  periodHangingOilLamp: { enabled: true, preload: false, path: '/assets/models/props/interiors/period-hanging-oil-lamp.glb', cacheKey: 'period-lighting-20260715a', scale: 1, rotation: [0, 0, 0], yOffset: 0, preserveMaterials: true, targetTriangles: 14000, prompt: '1830s hanging gimballed oil lamp with aged brass reservoir, burner gallery, glass chimney, iron chain and visible wick.' },
  periodTableOilLamp: { enabled: true, preload: false, path: '/assets/models/props/interiors/period-table-oil-lamp.glb', cacheKey: 'period-lighting-20260715a', scale: 1, rotation: [0, 0, 0], yOffset: 0, preserveMaterials: true, targetTriangles: 9000, prompt: '1830s table oil lamp with turned brass reservoir, burner gallery, thumb wheel and imperfect glass chimney.' },
  periodBrassCandlestick: { enabled: true, preload: false, path: '/assets/models/props/interiors/period-brass-candlestick.glb', cacheKey: 'period-lighting-20260715a', scale: 1, rotation: [0, 0, 0], yOffset: 0, preserveMaterials: true, targetTriangles: 6000, prompt: 'Turned 1830s brass candlestick with roughness variation, tallow candle, wax drips and blackened wick.' },
  beagleCabinCandlestick: { enabled: true, preload: false, path: '/assets/models/props/interiors/period-brass-candlestick.glb', cacheKey: 'period-lighting-20260715a', scale: 1, rotation: [0, 0, 0], yOffset: 0, preserveMaterials: true, targetTriangles: 6000, prompt: 'Shared turned brass cabin candlestick with tallow candle, wax drips and blackened wick.' },
  lawsonHouseInterior: {
    enabled: true,
    preload: false,
    path: '/assets/models/structures/lawson-house-interior.glb',
    cacheKey: 'lawson-house-bedroom-20260715c',
    scale: 1,
    rotation: [0, 0, 0],
    yOffset: 0,
    preserveMaterials: true,
    targetTriangles: 135000,
    // Procedurally built from the shared four-room blueprint by
    // scripts/blender_build_lawson_house.py.
    prompt: "Nicholas Lawson's damp 1835 Floreana government house interior: four-room weatherboard residence with an atmospheric entrance and dining room, open working office/library, veranda, and highland garden views.",
  },
  lawsonDiningChair: { enabled: true, preload: false, path: '/assets/models/props/lawson-house/dining-chair.glb', scale: 1, rotation: [0, 0, 0], yOffset: 0, preserveMaterials: true, targetTriangles: 5000, prompt: 'Mismatched spindle-back dining chair with rush seat, repaired for a remote 1830s settlement.' },
  lawsonCampaignStool: { enabled: true, preload: false, path: '/assets/models/props/lawson-house/campaign-stool.glb', scale: 1, rotation: [0, 0, 0], yOffset: 0, preserveMaterials: true, targetTriangles: 3500, prompt: 'Plain folding campaign stool with canvas seat and brass pivots.' },
  lawsonRumBottle: { enabled: true, preload: false, path: '/assets/models/props/lawson-house/rum-bottle.glb', scale: 1, rotation: [0, 0, 0], yOffset: 0, preserveMaterials: true, targetTriangles: 2500, prompt: 'Dark hand-blown rum bottle with cork and damp paper label.' },
  lawsonTinMug: { enabled: true, preload: false, path: '/assets/models/props/lawson-house/tin-mug.glb', scale: 1, rotation: [0, 0, 0], yOffset: 0, preserveMaterials: true, targetTriangles: 1800, prompt: 'Worn pewter or tinned mug with rolled rim.' },
  lawsonServingBowl: { enabled: true, preload: false, path: '/assets/models/props/lawson-house/serving-bowl.glb', scale: 1, rotation: [0, 0, 0], yOffset: 0, preserveMaterials: true, targetTriangles: 3500, prompt: 'Coarse earthenware serving bowl filled with sweet potatoes.' },
  lawsonFoldedChart: { enabled: true, preload: false, path: '/assets/models/props/lawson-house/folded-chart.glb', scale: 1, rotation: [0, 0, 0], yOffset: 0, preserveMaterials: true, targetTriangles: 1200, prompt: 'Damp folded maritime chart reused at the dining table.' },
  lawsonSupplyLedger: { enabled: true, preload: false, path: '/assets/models/props/lawson-house/supply-ledger.glb', scale: 1, rotation: [0, 0, 0], yOffset: 0, preserveMaterials: true, targetTriangles: 1500, prompt: 'Leather-bound bilingual colony supply ledger with paper label.' },
  lawsonCandlestick: { enabled: true, preload: false, path: '/assets/models/props/interiors/period-brass-candlestick.glb', cacheKey: 'period-lighting-20260715a', scale: 1.08, rotation: [0, 0, 0], yOffset: 0, preserveMaterials: true, targetTriangles: 6000, prompt: 'Shared turned brass candlestick with a well-used tallow candle, wax drips and blackened wick.' },
  // --- Penal colony settlement structures (Tripo, unit-normalized; scale ==
  // target real-world size in meters). Prepared by
  // scripts/prepare-penal-colony-assets.mjs into /assets/models/structures/.
  governorsHouse: {
    enabled: true,
    preload: false,
    path: '/assets/models/structures/governors-house.glb',
    scale: 11,
    rotation: [0, 0, 0],
    yOffset: 0,
    normalizeMaterials: true,
    materialLift: 0.04,
    materialEmissive: '#1b1410',
    materialEmissiveIntensity: 0.04,
    targetTriangles: 6600,
    prompt: 'Vice-Governor Nicholas Lawson residence, 1830s Floreana penal colony, low wide plank house with veranda.',
  },
  barracksCabin: {
    enabled: true,
    preload: false,
    path: '/assets/models/structures/barracks-cabin.glb',
    scale: 10,
    rotation: [0, 0, 0],
    yOffset: 0,
    normalizeMaterials: true,
    materialLift: 0.04,
    materialEmissive: '#1b1410',
    materialEmissiveIntensity: 0.04,
    targetTriangles: 2200,
    prompt: 'Long low wooden soldiers barracks cabin for the 1830s Floreana settlement.',
  },
  thatchedHutA: {
    enabled: true,
    preload: false,
    path: '/assets/models/structures/thatched-hut-a.glb',
    scale: 6,
    rotation: [0, 0, 0],
    yOffset: 0,
    normalizeMaterials: true,
    materialLift: 0.04,
    materialEmissive: '#1b1410',
    materialEmissiveIntensity: 0.04,
    targetTriangles: 2100,
    prompt: 'Small thatched settler hut, variant A, 1830s Floreana penal colony.',
  },
  thatchedHutB: {
    enabled: true,
    preload: false,
    path: '/assets/models/structures/thatched-hut-b.glb',
    scale: 5.6,
    rotation: [0, 0, 0],
    yOffset: 0,
    normalizeMaterials: true,
    materialLift: 0.04,
    materialEmissive: '#1b1410',
    materialEmissiveIntensity: 0.04,
    targetTriangles: 2400,
    prompt: 'Small thatched settler hut, variant B, 1830s Floreana penal colony.',
  },
  penalShack: {
    enabled: true,
    preload: false,
    path: '/assets/models/structures/penal-shack.glb',
    scale: 4.6,
    rotation: [0, 0, 0],
    yOffset: 0,
    normalizeMaterials: true,
    materialLift: 0.04,
    materialEmissive: '#1b1410',
    materialEmissiveIntensity: 0.04,
    targetTriangles: 2200,
    prompt: 'Ramshackle convict shack of rough planks, 1830s Floreana penal colony.',
  },
  threshingHut: {
    enabled: true,
    preload: false,
    path: '/assets/models/structures/threshing-hut.glb',
    scale: 6.4,
    rotation: [0, 0, 0],
    yOffset: 0,
    normalizeMaterials: true,
    materialLift: 0.04,
    materialEmissive: '#1b1410',
    materialEmissiveIntensity: 0.04,
    targetTriangles: 6300,
    prompt: 'Open-sided grain threshing hut with work floor, 1830s settlement agriculture.',
  },
  animalLeanto: {
    enabled: true,
    preload: false,
    path: '/assets/models/structures/animal-leanto.glb',
    scale: 5.6,
    rotation: [0, 0, 0],
    yOffset: 0,
    normalizeMaterials: true,
    materialLift: 0.04,
    materialEmissive: '#1b1410',
    materialEmissiveIntensity: 0.04,
    targetTriangles: 6500,
    prompt: 'Rough animal lean-to farm shelter of poles and thatch.',
  },
  animalPaddock: {
    enabled: true,
    preload: false,
    path: '/assets/models/structures/animal-paddock.glb',
    scale: 4.2,
    rotation: [0, 0, 0],
    yOffset: 0,
    normalizeMaterials: true,
    materialLift: 0.04,
    materialEmissive: '#1b1410',
    materialEmissiveIntensity: 0.04,
    targetTriangles: 6600,
    prompt: 'Small wooden animal paddock enclosure of crude rails.',
  },
  outhouse: {
    enabled: true,
    preload: false,
    path: '/assets/models/structures/outhouse.glb',
    scale: 2.4,
    rotation: [0, 0, 0],
    yOffset: 0,
    normalizeMaterials: true,
    materialLift: 0.04,
    materialEmissive: '#1b1410',
    materialEmissiveIntensity: 0.04,
    targetTriangles: 2200,
    prompt: 'Weathered wooden outhouse at the settlement edge.',
  },
  settlementFenceA: {
    enabled: true,
    preload: false,
    path: '/assets/models/structures/fence-run-a.glb',
    scale: 4.2,
    rotation: [0, 0, 0],
    yOffset: 0,
    normalizeMaterials: true,
    materialLift: 0.04,
    materialEmissive: '#1b1410',
    materialEmissiveIntensity: 0.04,
    targetTriangles: 2000,
    prompt: 'Crude post-and-rail fence module (split from gate/fence vignette); run axis along local Z.',
  },
  settlementFenceB: {
    enabled: true,
    preload: false,
    path: '/assets/models/structures/fence-run-b.glb',
    scale: 4.2,
    rotation: [0, 0, 0],
    yOffset: 0,
    normalizeMaterials: true,
    materialLift: 0.04,
    materialEmissive: '#1b1410',
    materialEmissiveIntensity: 0.04,
    targetTriangles: 2000,
    prompt: 'Crude post-and-rail fence module, second variant; run axis along local Z.',
  },
  settlementGate: {
    enabled: true,
    preload: false,
    path: '/assets/models/structures/settlement-gate.glb',
    scale: 4.4,
    rotation: [0, 0, 0],
    yOffset: 0,
    normalizeMaterials: true,
    materialLift: 0.04,
    materialEmissive: '#1b1410',
    materialEmissiveIntensity: 0.04,
    targetTriangles: 4500,
    prompt: 'Framed wooden settlement gate with arbor beams (split from gate/fence vignette).',
  },
  settlementBarrel: {
    enabled: true,
    preload: false,
    path: '/assets/models/structures/settlement-barrel.glb',
    scale: 1.05,
    rotation: [0, 0, 0],
    yOffset: 0,
    normalizeMaterials: true,
    materialLift: 0.04,
    materialEmissive: '#1b1209',
    materialEmissiveIntensity: 0.04,
    targetTriangles: 2400,
    prompt: 'Weathered settlement storage barrel.',
  },
  cratesAndBags: {
    enabled: true,
    preload: false,
    path: '/assets/models/structures/crates-and-bags.glb',
    scale: 2.4,
    rotation: [0, 0, 0],
    yOffset: 0,
    normalizeMaterials: true,
    materialLift: 0.04,
    materialEmissive: '#1b1209',
    materialEmissiveIntensity: 0.04,
    targetTriangles: 2400,
    prompt: 'Wooden crates and grain bags supply clutter pile.',
  },
  wheelbarrow: {
    enabled: true,
    preload: false,
    path: '/assets/models/structures/wheelbarrow.glb',
    scale: 1.7,
    rotation: [0, 0, 0],
    yOffset: 0,
    normalizeMaterials: true,
    materialLift: 0.04,
    materialEmissive: '#1b1209',
    materialEmissiveIntensity: 0.04,
    targetTriangles: 9400,
    prompt: 'Wooden field wheelbarrow, pushable settlement prop.',
  },
  waterTrough: {
    enabled: true,
    preload: false,
    path: '/assets/models/structures/water-trough.glb',
    scale: 2.6,
    rotation: [0, 0, 0],
    yOffset: 0,
    normalizeMaterials: true,
    materialLift: 0.04,
    materialEmissive: '#1b1209',
    materialEmissiveIntensity: 0.04,
    targetTriangles: 450,
    prompt: 'Wooden water trough (split from stable vignette).',
  },
  hitchingPost: {
    enabled: true,
    preload: false,
    path: '/assets/models/structures/hitching-post.glb',
    scale: 1.9,
    rotation: [0, 0, 0],
    yOffset: 0,
    normalizeMaterials: true,
    materialLift: 0.04,
    materialEmissive: '#1b1209',
    materialEmissiveIntensity: 0.04,
    targetTriangles: 2900,
    prompt: 'Hitching post with rail and iron rings (split from stable vignette).',
  },
  woodenBucket: {
    enabled: true,
    preload: false,
    path: '/assets/models/structures/wooden-bucket.glb',
    scale: 1.6,
    rotation: [0, 0, 0],
    yOffset: 0,
    normalizeMaterials: true,
    materialLift: 0.04,
    materialEmissive: '#1b1209',
    materialEmissiveIntensity: 0.04,
    targetTriangles: 1600,
    prompt: 'Small stave wooden bucket (split from stable vignette).',
  },
};

/**
 * @param {string} id
 * @returns {ModelAssetConfig | null}
 */
export function getModelAsset(id) {
  return modelAssets[id] || null;
}
