const GRASS_HYBRID_TEST = 'GRASS_HYBRID_TEST';

export function buildGrassHybridTestEcology() {
  return {
    zoneId: GRASS_HYBRID_TEST,
    stream: false,
    denseGrass: [
      {
        id: 'hybrid-test-near-interactive-blades',
        count: 42000,
        seed: 8221,
        bounds: { minX: -36, maxX: 36, minZ: -34, maxZ: 34 },
        height: [0.18, 0.82],
        width: [0.008, 0.026],
        coverage: 0.82,
        minCoverage: 0.38,
        patchScale: 0.055,
        tuftScale: 0.2,
        clusterScale: 0.052,
        clusterStrength: 0.5,
        heightClusterScale: 0.02,
        directionScale: 0.052,
        windDirectionBias: 0.82,
        yawJitter: 0.28,
        pathAware: true,
        maxGrade: 0.9,
        baseLift: 0.018,
        tipBend: 0.62,
        prelean: 0.55,
        windAmp: 0.18,
        bendAmp: 2.25,
        bendRadius: 2.9,
        contactRadius: 1.55,
        recoveryRate: 0.09,
        fadeFarStart: 10,
        fadeFarEnd: 16,
        dryness: 0.18,
        dryPatchStrength: 0.28,
        colorVariance: 0.32,
        deepColor: '#243f28',
        rootColor: '#4d6d36',
        midColor: '#849e4d',
        tipColor: '#bcc56c',
        dryColor: '#98884a',
        dryTipColor: '#d4c378',
      },
    ],
    hybridGrassTufts: [
      {
        id: 'hybrid-test-mid-tuft-impostors',
        count: 5200,
        seed: 9911,
        bounds: { minX: -38, maxX: 38, minZ: -36, maxZ: 36 },
        cardsPerTuft: 2,
        height: [0.34, 0.86],
        width: [0.42, 1.05],
        coverage: 0.54,
        clusterScale: 0.06,
        directionScale: 0.042,
        windDirectionBias: 0.84,
        windYaw: -0.72,
        windAmp: 0.12,
        pathAware: true,
        maxGrade: 0.9,
        baseLift: 0.015,
        fadeNear: 9,
        fadeFar: 34,
        dryness: 0.22,
        dryPatchStrength: 0.34,
        greenColor: '#78934a',
        dryColor: '#b29b55',
        darkColor: '#2b4729',
      },
    ],
    footprintBiomes: ['hybrid-meadow', 'dark-underbrush', 'dry-meadow-rise', 'trampled-grass-edge'],
    flora: [],
    rocks: [],
    props: [],
    birds: [
      { radius: 21, height: 15, speed: 0.1, phase: 1.2, cx: -8, cz: -5 },
      { radius: 26, height: 18, speed: -0.07, phase: 3.9, cx: 13, cz: 6 },
    ],
  };
}
